# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountPosition.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dockWidget(object):
    def setupUi(self, dockWidget):
        dockWidget.setObjectName(_fromUtf8("dockWidget"))
        dockWidget.resize(1034, 90)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_3 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 0, 14, 1, 1)
        self.pb_IFFuture = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_IFFuture.setFont(font)
        self.pb_IFFuture.setFlat(True)
        self.pb_IFFuture.setObjectName(_fromUtf8("pb_IFFuture"))
        self.gridLayout.addWidget(self.pb_IFFuture, 1, 9, 1, 1)
        self.pb_totalCash = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_totalCash.setFont(font)
        self.pb_totalCash.setFlat(True)
        self.pb_totalCash.setObjectName(_fromUtf8("pb_totalCash"))
        self.gridLayout.addWidget(self.pb_totalCash, 1, 14, 1, 1)
        self.pb_ICFuture = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_ICFuture.setFont(font)
        self.pb_ICFuture.setFlat(True)
        self.pb_ICFuture.setObjectName(_fromUtf8("pb_ICFuture"))
        self.gridLayout.addWidget(self.pb_ICFuture, 1, 13, 1, 1)
        self.pb_SZStock = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_SZStock.setFont(font)
        self.pb_SZStock.setFlat(True)
        self.pb_SZStock.setObjectName(_fromUtf8("pb_SZStock"))
        self.gridLayout.addWidget(self.pb_SZStock, 1, 8, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout.addWidget(self.pushButton_9, 0, 7, 1, 1)
        self.pb_sellFreeze = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_sellFreeze.setFont(font)
        self.pb_sellFreeze.setFlat(True)
        self.pb_sellFreeze.setObjectName(_fromUtf8("pb_sellFreeze"))
        self.gridLayout.addWidget(self.pb_sellFreeze, 1, 4, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 0, 13, 1, 1)
        self.pb_SHStock = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_SHStock.setFont(font)
        self.pb_SHStock.setFlat(True)
        self.pb_SHStock.setObjectName(_fromUtf8("pb_SHStock"))
        self.gridLayout.addWidget(self.pb_SHStock, 1, 7, 1, 1)
        self.pb_stockCanUse = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_stockCanUse.setFont(font)
        self.pb_stockCanUse.setFlat(True)
        self.pb_stockCanUse.setObjectName(_fromUtf8("pb_stockCanUse"))
        self.gridLayout.addWidget(self.pb_stockCanUse, 1, 0, 1, 1)
        self.pb_futrureCanUse = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_futrureCanUse.setFont(font)
        self.pb_futrureCanUse.setFlat(True)
        self.pb_futrureCanUse.setObjectName(_fromUtf8("pb_futrureCanUse"))
        self.gridLayout.addWidget(self.pb_futrureCanUse, 1, 1, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setFlat(True)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout.addWidget(self.pushButton_13, 0, 11, 1, 1)
        self.pb_buyFreeze = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_buyFreeze.setFont(font)
        self.pb_buyFreeze.setFlat(True)
        self.pb_buyFreeze.setObjectName(_fromUtf8("pb_buyFreeze"))
        self.gridLayout.addWidget(self.pb_buyFreeze, 1, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 0, 9, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 0, 4, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout.addWidget(self.pushButton_11, 0, 8, 1, 1)
        self.pb_IHFuture = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_IHFuture.setFont(font)
        self.pb_IHFuture.setFlat(True)
        self.pb_IHFuture.setObjectName(_fromUtf8("pb_IHFuture"))
        self.gridLayout.addWidget(self.pb_IHFuture, 1, 11, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout.addWidget(self.pushButton_10, 0, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        dockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(dockWidget)
        QtCore.QMetaObject.connectSlotsByName(dockWidget)

    def retranslateUi(self, dockWidget):
        dockWidget.setWindowTitle(_translate("dockWidget", "头寸监控", None))
        self.pushButton_3.setText(_translate("dockWidget", "总头寸（万）", None))
        self.pb_IFFuture.setText(_translate("dockWidget", "0", None))
        self.pb_totalCash.setText(_translate("dockWidget", "0", None))
        self.pb_ICFuture.setText(_translate("dockWidget", "0", None))
        self.pb_SZStock.setText(_translate("dockWidget", "0", None))
        self.pushButton_9.setText(_translate("dockWidget", "沪股票（万）", None))
        self.pb_sellFreeze.setText(_translate("dockWidget", "0", None))
        self.pushButton_4.setText(_translate("dockWidget", "IC期货仓单数", None))
        self.pb_SHStock.setText(_translate("dockWidget", "0", None))
        self.pb_stockCanUse.setText(_translate("dockWidget", "0", None))
        self.pb_futrureCanUse.setText(_translate("dockWidget", "0", None))
        self.pushButton_13.setText(_translate("dockWidget", "IH期货仓单数", None))
        self.pb_buyFreeze.setText(_translate("dockWidget", "0", None))
        self.pushButton_2.setText(_translate("dockWidget", "IF期货仓单数", None))
        self.pushButton_7.setText(_translate("dockWidget", "卖出冻结（万）", None))
        self.pushButton_11.setText(_translate("dockWidget", "深股票（万）", None))
        self.pb_IHFuture.setText(_translate("dockWidget", "0", None))
        self.pushButton_10.setText(_translate("dockWidget", "买入冻结（万）", None))
        self.pushButton_8.setText(_translate("dockWidget", "期货可用（万）", None))
        self.pushButton.setText(_translate("dockWidget", "现货可用（万）", None))

