# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BasketTrade.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(938, 769)
        DockWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pb_load = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_load.setObjectName(_fromUtf8("pb_load"))
        self.horizontalLayout_5.addWidget(self.pb_load)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.l_tdsx_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_tdsx_name.setObjectName(_fromUtf8("l_tdsx_name"))
        self.horizontalLayout_5.addWidget(self.l_tdsx_name)
        self.l_tdsx_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_tdsx_data.setObjectName(_fromUtf8("l_tdsx_data"))
        self.horizontalLayout_5.addWidget(self.l_tdsx_data)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.l_ccbfb_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_ccbfb_name.setObjectName(_fromUtf8("l_ccbfb_name"))
        self.horizontalLayout_5.addWidget(self.l_ccbfb_name)
        self.l_ccbfb_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_ccbfb_data.setObjectName(_fromUtf8("l_ccbfb_data"))
        self.horizontalLayout_5.addWidget(self.l_ccbfb_data)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.l_kshs_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_kshs_name.setObjectName(_fromUtf8("l_kshs_name"))
        self.horizontalLayout_5.addWidget(self.l_kshs_name)
        self.l_kshs_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_kshs_data.setObjectName(_fromUtf8("l_kshs_data"))
        self.horizontalLayout_5.addWidget(self.l_kshs_data)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pb_redeem = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_redeem.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(1, 208, 25); }\n"
""))
        self.pb_redeem.setObjectName(_fromUtf8("pb_redeem"))
        self.gridLayout_3.addWidget(self.pb_redeem, 0, 4, 1, 1)
        self.pb_basket_buy = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_basket_buy.setStyleSheet(_fromUtf8("QPushButton { background-color: rgb(255, 85, 0); }"))
        self.pb_basket_buy.setObjectName(_fromUtf8("pb_basket_buy"))
        self.gridLayout_3.addWidget(self.pb_basket_buy, 1, 3, 1, 1)
        self.pb_subscribe = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_subscribe.setStyleSheet(_fromUtf8("QPushButton { background-color: rgb(255, 85, 0); }"))
        self.pb_subscribe.setObjectName(_fromUtf8("pb_subscribe"))
        self.gridLayout_3.addWidget(self.pb_subscribe, 1, 4, 1, 1)
        self.pb_basket_sell = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_basket_sell.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(1, 208, 25); }\n"
""))
        self.pb_basket_sell.setObjectName(_fromUtf8("pb_basket_sell"))
        self.gridLayout_3.addWidget(self.pb_basket_sell, 0, 3, 1, 1)
        self.pb_complement = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_complement.setObjectName(_fromUtf8("pb_complement"))
        self.gridLayout_3.addWidget(self.pb_complement, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.pb_replace_complement = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_replace_complement.setObjectName(_fromUtf8("pb_replace_complement"))
        self.gridLayout_3.addWidget(self.pb_replace_complement, 0, 6, 1, 1)
        self.pb_refresh = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_refresh.setObjectName(_fromUtf8("pb_refresh"))
        self.gridLayout_3.addWidget(self.pb_refresh, 0, 7, 1, 1)
        self.cb_stock_name = QtGui.QComboBox(self.dockWidgetContents)
        self.cb_stock_name.setEditable(False)
        self.cb_stock_name.setMaxVisibleItems(10)
        self.cb_stock_name.setFrame(True)
        self.cb_stock_name.setObjectName(_fromUtf8("cb_stock_name"))
        self.gridLayout_3.addWidget(self.cb_stock_name, 0, 1, 1, 1)
        self.pb_cancel = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.gridLayout_3.addWidget(self.pb_cancel, 1, 5, 1, 1)
        self.pb_auto_cancel_supplement = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_auto_cancel_supplement.setObjectName(_fromUtf8("pb_auto_cancel_supplement"))
        self.gridLayout_3.addWidget(self.pb_auto_cancel_supplement, 1, 7, 1, 1)
        self.l_stock_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_stock_name.setObjectName(_fromUtf8("l_stock_name"))
        self.gridLayout_3.addWidget(self.l_stock_name, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 2, 1, 1)
        self.le_order_num = QtGui.QLineEdit(self.dockWidgetContents)
        self.le_order_num.setObjectName(_fromUtf8("le_order_num"))
        self.gridLayout_3.addWidget(self.le_order_num, 1, 1, 1, 1)
        self.l_order_num = QtGui.QLabel(self.dockWidgetContents)
        self.l_order_num.setObjectName(_fromUtf8("l_order_num"))
        self.gridLayout_3.addWidget(self.l_order_num, 1, 0, 1, 1)
        self.pb_supplement = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_supplement.setObjectName(_fromUtf8("pb_supplement"))
        self.gridLayout_3.addWidget(self.pb_supplement, 1, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pb_choose_basket = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_choose_basket.setObjectName(_fromUtf8("pb_choose_basket"))
        self.horizontalLayout_4.addWidget(self.pb_choose_basket)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.l_basket_dirt_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_basket_dirt_name.setObjectName(_fromUtf8("l_basket_dirt_name"))
        self.horizontalLayout_4.addWidget(self.l_basket_dirt_name)
        self.l_basket_dirt_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_basket_dirt_data.setObjectName(_fromUtf8("l_basket_dirt_data"))
        self.horizontalLayout_4.addWidget(self.l_basket_dirt_data)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.l_cur_policy_id_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_cur_policy_id_name.setObjectName(_fromUtf8("l_cur_policy_id_name"))
        self.horizontalLayout_4.addWidget(self.l_cur_policy_id_name)
        self.l_cur_policy_id_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_cur_policy_id_data.setObjectName(_fromUtf8("l_cur_policy_id_data"))
        self.horizontalLayout_4.addWidget(self.l_cur_policy_id_data)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.l_deal_iopv_name_2 = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_iopv_name_2.setObjectName(_fromUtf8("l_deal_iopv_name_2"))
        self.gridLayout_2.addWidget(self.l_deal_iopv_name_2, 0, 3, 1, 1)
        self.pb_usable_fund_name = QtGui.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pb_usable_fund_name.setFont(font)
        self.pb_usable_fund_name.setMouseTracking(False)
        self.pb_usable_fund_name.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.pb_usable_fund_name.setFlat(True)
        self.pb_usable_fund_name.setObjectName(_fromUtf8("pb_usable_fund_name"))
        self.gridLayout_2.addWidget(self.pb_usable_fund_name, 0, 1, 1, 1)
        self.l_deal_money_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_money_name.setObjectName(_fromUtf8("l_deal_money_name"))
        self.gridLayout_2.addWidget(self.l_deal_money_name, 2, 1, 1, 1)
        self.l_estimate_cost_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_estimate_cost_name.setObjectName(_fromUtf8("l_estimate_cost_name"))
        self.gridLayout_2.addWidget(self.l_estimate_cost_name, 1, 1, 1, 1)
        self.l_deal_iopv_name_4 = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_iopv_name_4.setObjectName(_fromUtf8("l_deal_iopv_name_4"))
        self.gridLayout_2.addWidget(self.l_deal_iopv_name_4, 2, 3, 1, 1)
        self.l_usable_fund_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_usable_fund_data.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_usable_fund_data.setObjectName(_fromUtf8("l_usable_fund_data"))
        self.gridLayout_2.addWidget(self.l_usable_fund_data, 0, 2, 1, 1)
        self.l_deal_iopv_name_5 = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_iopv_name_5.setObjectName(_fromUtf8("l_deal_iopv_name_5"))
        self.gridLayout_2.addWidget(self.l_deal_iopv_name_5, 3, 3, 1, 1)
        self.l_percent_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_percent_name.setObjectName(_fromUtf8("l_percent_name"))
        self.gridLayout_2.addWidget(self.l_percent_name, 4, 1, 1, 1)
        self.l_percent_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_percent_data.setObjectName(_fromUtf8("l_percent_data"))
        self.gridLayout_2.addWidget(self.l_percent_data, 4, 2, 1, 1)
        self.l_deal_iopv_name_3 = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_iopv_name_3.setObjectName(_fromUtf8("l_deal_iopv_name_3"))
        self.gridLayout_2.addWidget(self.l_deal_iopv_name_3, 1, 3, 1, 1)
        self.l_deal_iopv_name = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_iopv_name.setObjectName(_fromUtf8("l_deal_iopv_name"))
        self.gridLayout_2.addWidget(self.l_deal_iopv_name, 3, 1, 1, 1)
        self.l_deal_money_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_money_data.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_deal_money_data.setObjectName(_fromUtf8("l_deal_money_data"))
        self.gridLayout_2.addWidget(self.l_deal_money_data, 2, 2, 1, 1)
        self.l_deal_iopv_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_deal_iopv_data.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_deal_iopv_data.setObjectName(_fromUtf8("l_deal_iopv_data"))
        self.gridLayout_2.addWidget(self.l_deal_iopv_data, 3, 2, 1, 1)
        self.l_estimate_cost_data = QtGui.QLabel(self.dockWidgetContents)
        self.l_estimate_cost_data.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_estimate_cost_data.setObjectName(_fromUtf8("l_estimate_cost_data"))
        self.gridLayout_2.addWidget(self.l_estimate_cost_data, 1, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 4, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tv_basket_list = QtGui.QTableWidget(self.dockWidgetContents)
        self.tv_basket_list.setObjectName(_fromUtf8("tv_basket_list"))
        self.tv_basket_list.setColumnCount(13)
        self.tv_basket_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tv_basket_list.setHorizontalHeaderItem(12, item)
        self.tv_basket_list.horizontalHeader().setDefaultSectionSize(70)
        self.horizontalLayout.addWidget(self.tv_basket_list)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "篮子买卖", None))
        self.pb_load.setText(_translate("DockWidget", "导入篮子", None))
        self.l_tdsx_name.setText(_translate("DockWidget", "现金替代上限：", None))
        self.l_tdsx_data.setText(_translate("DockWidget", "50%", None))
        self.l_ccbfb_name.setText(_translate("DockWidget", "持仓百分比：", None))
        self.l_ccbfb_data.setText(_translate("DockWidget", "50%", None))
        self.l_kshs_name.setText(_translate("DockWidget", "可赎回数：", None))
        self.l_kshs_data.setText(_translate("DockWidget", "5", None))
        self.pb_redeem.setText(_translate("DockWidget", "赎回", None))
        self.pb_basket_buy.setText(_translate("DockWidget", "篮子买入", None))
        self.pb_subscribe.setText(_translate("DockWidget", "申购", None))
        self.pb_basket_sell.setText(_translate("DockWidget", "篮子卖出", None))
        self.pb_complement.setText(_translate("DockWidget", "补足", None))
        self.pb_replace_complement.setText(_translate("DockWidget", "替代补足", None))
        self.pb_refresh.setText(_translate("DockWidget", "刷新", None))
        self.pb_cancel.setText(_translate("DockWidget", "撤单", None))
        self.pb_auto_cancel_supplement.setText(_translate("DockWidget", "自动撤补", None))
        self.l_stock_name.setText(_translate("DockWidget", "证券代码", None))
        self.l_order_num.setText(_translate("DockWidget", "委托数量", None))
        self.pb_supplement.setText(_translate("DockWidget", "补单", None))
        self.pb_choose_basket.setText(_translate("DockWidget", "选择未完成篮子", None))
        self.l_basket_dirt_name.setText(_translate("DockWidget", "篮子买卖方向：", None))
        self.l_basket_dirt_data.setText(_translate("DockWidget", "买入", None))
        self.l_cur_policy_id_name.setText(_translate("DockWidget", "当前策略ID：", None))
        self.l_cur_policy_id_data.setText(_translate("DockWidget", "0001", None))
        self.l_deal_iopv_name_2.setText(_translate("DockWidget", "万", None))
        self.pb_usable_fund_name.setText(_translate("DockWidget", "可用资金：", None))
        self.l_deal_money_name.setText(_translate("DockWidget", "已成金额：", None))
        self.l_estimate_cost_name.setText(_translate("DockWidget", "预估成本：", None))
        self.l_deal_iopv_name_4.setText(_translate("DockWidget", "万", None))
        self.l_usable_fund_data.setText(_translate("DockWidget", "11,111.59", None))
        self.l_deal_iopv_name_5.setText(_translate("DockWidget", "万", None))
        self.l_percent_name.setText(_translate("DockWidget", "完成百分比：", None))
        self.l_percent_data.setText(_translate("DockWidget", "30%", None))
        self.l_deal_iopv_name_3.setText(_translate("DockWidget", "万", None))
        self.l_deal_iopv_name.setText(_translate("DockWidget", "已成净值：", None))
        self.l_deal_money_data.setText(_translate("DockWidget", "1,234.01", None))
        self.l_deal_iopv_data.setText(_translate("DockWidget", "2.12938", None))
        self.l_estimate_cost_data.setText(_translate("DockWidget", "12.00", None))
        item = self.tv_basket_list.horizontalHeaderItem(0)
        item.setText(_translate("DockWidget", "代码", None))
        item = self.tv_basket_list.horizontalHeaderItem(1)
        item.setText(_translate("DockWidget", "名称", None))
        item = self.tv_basket_list.horizontalHeaderItem(2)
        item.setText(_translate("DockWidget", "数量", None))
        item = self.tv_basket_list.horizontalHeaderItem(3)
        item.setText(_translate("DockWidget", "替代标记", None))
        item = self.tv_basket_list.horizontalHeaderItem(4)
        item.setText(_translate("DockWidget", "溢价比例", None))
        item = self.tv_basket_list.horizontalHeaderItem(5)
        item.setText(_translate("DockWidget", "替代金额", None))
        item = self.tv_basket_list.horizontalHeaderItem(6)
        item.setText(_translate("DockWidget", "状态", None))
        item = self.tv_basket_list.horizontalHeaderItem(7)
        item.setText(_translate("DockWidget", "持仓数", None))
        item = self.tv_basket_list.horizontalHeaderItem(8)
        item.setText(_translate("DockWidget", "可卖数", None))
        item = self.tv_basket_list.horizontalHeaderItem(9)
        item.setText(_translate("DockWidget", "缺口量", None))
        item = self.tv_basket_list.horizontalHeaderItem(10)
        item.setText(_translate("DockWidget", "今买入", None))
        item = self.tv_basket_list.horizontalHeaderItem(11)
        item.setText(_translate("DockWidget", "盘口", None))
        item = self.tv_basket_list.horizontalHeaderItem(12)
        item.setText(_translate("DockWidget", "盘口价", None))

