# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ETFOrderCollectOne.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName(_fromUtf8("GroupBox"))
        GroupBox.resize(400, 290)
        GroupBox.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    border: 2px solid rgb(29, 233, 255)\n"
"};"))
        GroupBox.setTitle(_fromUtf8(""))
        self.gb_pb_b1_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_b1_volume.setGeometry(QtCore.QRect(110, 160, 71, 20))
        self.gb_pb_b1_volume.setFlat(True)
        self.gb_pb_b1_volume.setObjectName(_fromUtf8("gb_pb_b1_volume"))
        self.gb_pb_buy_volume_row_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_3.setGeometry(QtCore.QRect(210, 200, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_row_3.setFont(font)
        self.gb_pb_buy_volume_row_3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_row_3.setFlat(True)
        self.gb_pb_buy_volume_row_3.setObjectName(_fromUtf8("gb_pb_buy_volume_row_3"))
        self.gb_pb_sell_volume_row_4 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_4.setGeometry(QtCore.QRect(210, 60, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_row_4.setFont(font)
        self.gb_pb_sell_volume_row_4.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_row_4.setText(_fromUtf8(""))
        self.gb_pb_sell_volume_row_4.setFlat(True)
        self.gb_pb_sell_volume_row_4.setObjectName(_fromUtf8("gb_pb_sell_volume_row_4"))
        self.gb_pb_sell_volume_total_minus = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_total_minus.setGeometry(QtCore.QRect(240, 10, 31, 23))
        self.gb_pb_sell_volume_total_minus.setObjectName(_fromUtf8("gb_pb_sell_volume_total_minus"))
        self.gb_pb_s2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_s2.setGeometry(QtCore.QRect(10, 100, 41, 20))
        self.gb_pb_s2.setFlat(True)
        self.gb_pb_s2.setObjectName(_fromUtf8("gb_pb_s2"))
        self.gb_pb_buy_volume_1_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_1_1.setGeometry(QtCore.QRect(270, 160, 41, 23))
        self.gb_pb_buy_volume_1_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_1_1.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_1_1.setObjectName(_fromUtf8("gb_pb_buy_volume_1_1"))
        self.gb_pb_sell_volume_column_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_column_2.setGeometry(QtCore.QRect(310, 10, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_column_2.setFont(font)
        self.gb_pb_sell_volume_column_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_column_2.setFlat(True)
        self.gb_pb_sell_volume_column_2.setObjectName(_fromUtf8("gb_pb_sell_volume_column_2"))
        self.gb_pb_sell_volume_5_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_5_2.setGeometry(QtCore.QRect(310, 40, 41, 23))
        self.gb_pb_sell_volume_5_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_5_2.setObjectName(_fromUtf8("gb_pb_sell_volume_5_2"))
        self.gb_pb_b1_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_b1_price.setGeometry(QtCore.QRect(50, 160, 61, 20))
        self.gb_pb_b1_price.setFlat(True)
        self.gb_pb_b1_price.setObjectName(_fromUtf8("gb_pb_b1_price"))
        self.gb_pb_sell_volume_row_minus_5 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_minus_5.setGeometry(QtCore.QRect(180, 40, 31, 23))
        self.gb_pb_sell_volume_row_minus_5.setObjectName(_fromUtf8("gb_pb_sell_volume_row_minus_5"))
        self.gb_pb_s5 = QtGui.QPushButton(GroupBox)
        self.gb_pb_s5.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.gb_pb_s5.setFlat(True)
        self.gb_pb_s5.setObjectName(_fromUtf8("gb_pb_s5"))
        self.gb_pb_buy_volume_row_minus_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_minus_1.setGeometry(QtCore.QRect(180, 160, 31, 23))
        self.gb_pb_buy_volume_row_minus_1.setObjectName(_fromUtf8("gb_pb_buy_volume_row_minus_1"))
        self.gb_pb_b1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_b1.setGeometry(QtCore.QRect(10, 160, 41, 20))
        self.gb_pb_b1.setFlat(True)
        self.gb_pb_b1.setObjectName(_fromUtf8("gb_pb_b1"))
        self.gb_pb_buy_volume_1_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_1_2.setGeometry(QtCore.QRect(310, 160, 41, 23))
        self.gb_pb_buy_volume_1_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_1_2.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_1_2.setObjectName(_fromUtf8("gb_pb_buy_volume_1_2"))
        self.gb_pb_b4_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_b4_price.setGeometry(QtCore.QRect(50, 220, 61, 20))
        self.gb_pb_b4_price.setStyleSheet(_fromUtf8("\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_b4_price.setFlat(True)
        self.gb_pb_b4_price.setObjectName(_fromUtf8("gb_pb_b4_price"))
        self.gb_pb_buy_volume_row_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_1.setGeometry(QtCore.QRect(210, 160, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_row_1.setFont(font)
        self.gb_pb_buy_volume_row_1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_row_1.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_row_1.setFlat(True)
        self.gb_pb_buy_volume_row_1.setObjectName(_fromUtf8("gb_pb_buy_volume_row_1"))
        self.gb_pb_b2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_b2.setGeometry(QtCore.QRect(10, 180, 41, 20))
        self.gb_pb_b2.setFlat(True)
        self.gb_pb_b2.setObjectName(_fromUtf8("gb_pb_b2"))
        self.gb_pb_buy_volume_total_minus = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_total_minus.setGeometry(QtCore.QRect(240, 260, 31, 23))
        self.gb_pb_buy_volume_total_minus.setObjectName(_fromUtf8("gb_pb_buy_volume_total_minus"))
        self.gb_pb_b3_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_b3_price.setGeometry(QtCore.QRect(50, 200, 61, 20))
        self.gb_pb_b3_price.setFlat(True)
        self.gb_pb_b3_price.setObjectName(_fromUtf8("gb_pb_b3_price"))
        self.gb_pb_buy_volume_1_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_1_3.setGeometry(QtCore.QRect(350, 160, 41, 23))
        self.gb_pb_buy_volume_1_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_1_3.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_1_3.setObjectName(_fromUtf8("gb_pb_buy_volume_1_3"))
        self.gb_pb_sell_total_money = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_total_money.setGeometry(QtCore.QRect(100, 10, 81, 23))
        self.gb_pb_sell_total_money.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_total_money.setFlat(True)
        self.gb_pb_sell_total_money.setObjectName(_fromUtf8("gb_pb_sell_total_money"))
        self.gb_pb_b5_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_b5_price.setGeometry(QtCore.QRect(50, 240, 61, 20))
        self.gb_pb_b5_price.setStyleSheet(_fromUtf8(""))
        self.gb_pb_b5_price.setFlat(True)
        self.gb_pb_b5_price.setObjectName(_fromUtf8("gb_pb_b5_price"))
        self.gb_pb_buy_volume_row_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_2.setGeometry(QtCore.QRect(210, 180, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_row_2.setFont(font)
        self.gb_pb_buy_volume_row_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_row_2.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_row_2.setFlat(True)
        self.gb_pb_buy_volume_row_2.setObjectName(_fromUtf8("gb_pb_buy_volume_row_2"))
        self.gb_pb_buy_total_money = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_total_money.setGeometry(QtCore.QRect(100, 260, 81, 23))
        self.gb_pb_buy_total_money.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_total_money.setFlat(True)
        self.gb_pb_buy_total_money.setObjectName(_fromUtf8("gb_pb_buy_total_money"))
        self.gb_pb_sell_volume_5_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_5_1.setGeometry(QtCore.QRect(270, 40, 41, 23))
        self.gb_pb_sell_volume_5_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_5_1.setObjectName(_fromUtf8("gb_pb_sell_volume_5_1"))
        self.gb_pb_sell_volume_row_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_2.setGeometry(QtCore.QRect(210, 100, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_row_2.setFont(font)
        self.gb_pb_sell_volume_row_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_row_2.setText(_fromUtf8(""))
        self.gb_pb_sell_volume_row_2.setFlat(True)
        self.gb_pb_sell_volume_row_2.setObjectName(_fromUtf8("gb_pb_sell_volume_row_2"))
        self.gb_pb_s4 = QtGui.QPushButton(GroupBox)
        self.gb_pb_s4.setGeometry(QtCore.QRect(10, 60, 41, 20))
        self.gb_pb_s4.setFlat(True)
        self.gb_pb_s4.setObjectName(_fromUtf8("gb_pb_s4"))
        self.gb_pb_buy_volume_column_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_column_1.setGeometry(QtCore.QRect(270, 260, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_column_1.setFont(font)
        self.gb_pb_buy_volume_column_1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_column_1.setFlat(True)
        self.gb_pb_buy_volume_column_1.setObjectName(_fromUtf8("gb_pb_buy_volume_column_1"))
        self.gb_pb_b2_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_b2_price.setGeometry(QtCore.QRect(50, 180, 61, 20))
        self.gb_pb_b2_price.setFlat(True)
        self.gb_pb_b2_price.setObjectName(_fromUtf8("gb_pb_b2_price"))
        self.gb_pb_s2_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_s2_volume.setGeometry(QtCore.QRect(110, 100, 71, 20))
        self.gb_pb_s2_volume.setFlat(True)
        self.gb_pb_s2_volume.setObjectName(_fromUtf8("gb_pb_s2_volume"))
        self.gb_pb_s1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_s1.setGeometry(QtCore.QRect(10, 120, 41, 20))
        self.gb_pb_s1.setFlat(True)
        self.gb_pb_s1.setObjectName(_fromUtf8("gb_pb_s1"))
        self.gb_pb_b3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_b3.setGeometry(QtCore.QRect(10, 200, 41, 20))
        self.gb_pb_b3.setFlat(True)
        self.gb_pb_b3.setObjectName(_fromUtf8("gb_pb_b3"))
        self.gb_pb_buy_volume_row_4 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_4.setGeometry(QtCore.QRect(210, 220, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_row_4.setFont(font)
        self.gb_pb_buy_volume_row_4.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_row_4.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_row_4.setFlat(True)
        self.gb_pb_buy_volume_row_4.setObjectName(_fromUtf8("gb_pb_buy_volume_row_4"))
        self.gb_pb_sell_volume_column_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_column_3.setGeometry(QtCore.QRect(350, 10, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_column_3.setFont(font)
        self.gb_pb_sell_volume_column_3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_column_3.setFlat(True)
        self.gb_pb_sell_volume_column_3.setObjectName(_fromUtf8("gb_pb_sell_volume_column_3"))
        self.gb_pb_s4_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_s4_price.setGeometry(QtCore.QRect(50, 60, 61, 20))
        self.gb_pb_s4_price.setFlat(True)
        self.gb_pb_s4_price.setObjectName(_fromUtf8("gb_pb_s4_price"))
        self.gb_pb_s2_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_s2_price.setGeometry(QtCore.QRect(50, 100, 61, 20))
        self.gb_pb_s2_price.setStyleSheet(_fromUtf8("\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_s2_price.setFlat(True)
        self.gb_pb_s2_price.setObjectName(_fromUtf8("gb_pb_s2_price"))
        self.gb_pb_buy_volume_row_minus_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_minus_2.setGeometry(QtCore.QRect(180, 180, 31, 23))
        self.gb_pb_buy_volume_row_minus_2.setObjectName(_fromUtf8("gb_pb_buy_volume_row_minus_2"))
        self.gb_pb_sell_volume_column_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_column_1.setGeometry(QtCore.QRect(270, 10, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_column_1.setFont(font)
        self.gb_pb_sell_volume_column_1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_column_1.setFlat(True)
        self.gb_pb_sell_volume_column_1.setObjectName(_fromUtf8("gb_pb_sell_volume_column_1"))
        self.gb_pb_sell_volume_total = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_total.setGeometry(QtCore.QRect(210, 10, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_total.setFont(font)
        self.gb_pb_sell_volume_total.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_total.setFlat(True)
        self.gb_pb_sell_volume_total.setObjectName(_fromUtf8("gb_pb_sell_volume_total"))
        self.gb_pb_buy_volume_total = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_total.setGeometry(QtCore.QRect(210, 260, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_total.setFont(font)
        self.gb_pb_buy_volume_total.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_total.setFlat(True)
        self.gb_pb_buy_volume_total.setObjectName(_fromUtf8("gb_pb_buy_volume_total"))
        self.gb_pb_buy_volume_column_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_column_2.setGeometry(QtCore.QRect(310, 260, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_column_2.setFont(font)
        self.gb_pb_buy_volume_column_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_column_2.setFlat(True)
        self.gb_pb_buy_volume_column_2.setObjectName(_fromUtf8("gb_pb_buy_volume_column_2"))
        self.gb_pb_sell_volume_row_5 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_5.setGeometry(QtCore.QRect(210, 40, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_row_5.setFont(font)
        self.gb_pb_sell_volume_row_5.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_row_5.setFlat(True)
        self.gb_pb_sell_volume_row_5.setObjectName(_fromUtf8("gb_pb_sell_volume_row_5"))
        self.gb_pb_b3_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_b3_volume.setGeometry(QtCore.QRect(110, 200, 71, 20))
        self.gb_pb_b3_volume.setFlat(True)
        self.gb_pb_b3_volume.setObjectName(_fromUtf8("gb_pb_b3_volume"))
        self.gb_pb_sell_volume_row_minus_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_minus_2.setGeometry(QtCore.QRect(180, 100, 31, 23))
        self.gb_pb_sell_volume_row_minus_2.setObjectName(_fromUtf8("gb_pb_sell_volume_row_minus_2"))
        self.gb_pb_s3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_s3.setGeometry(QtCore.QRect(10, 80, 41, 20))
        self.gb_pb_s3.setFlat(True)
        self.gb_pb_s3.setObjectName(_fromUtf8("gb_pb_s3"))
        self.gb_pb_s3_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_s3_volume.setGeometry(QtCore.QRect(110, 80, 71, 20))
        self.gb_pb_s3_volume.setFlat(True)
        self.gb_pb_s3_volume.setObjectName(_fromUtf8("gb_pb_s3_volume"))
        self.gb_pb_sell_volume_row_minus_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_minus_3.setGeometry(QtCore.QRect(180, 80, 31, 23))
        self.gb_pb_sell_volume_row_minus_3.setObjectName(_fromUtf8("gb_pb_sell_volume_row_minus_3"))
        self.gb_pb_buy_volume_column_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_column_3.setGeometry(QtCore.QRect(350, 260, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_column_3.setFont(font)
        self.gb_pb_buy_volume_column_3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_column_3.setFlat(True)
        self.gb_pb_buy_volume_column_3.setObjectName(_fromUtf8("gb_pb_buy_volume_column_3"))
        self.gb_pb_b4_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_b4_volume.setGeometry(QtCore.QRect(110, 220, 71, 20))
        self.gb_pb_b4_volume.setFlat(True)
        self.gb_pb_b4_volume.setObjectName(_fromUtf8("gb_pb_b4_volume"))
        self.gb_pb_s4_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_s4_volume.setGeometry(QtCore.QRect(110, 60, 71, 20))
        self.gb_pb_s4_volume.setFlat(True)
        self.gb_pb_s4_volume.setObjectName(_fromUtf8("gb_pb_s4_volume"))
        self.gb_pb_b4 = QtGui.QPushButton(GroupBox)
        self.gb_pb_b4.setGeometry(QtCore.QRect(10, 220, 41, 20))
        self.gb_pb_b4.setFlat(True)
        self.gb_pb_b4.setObjectName(_fromUtf8("gb_pb_b4"))
        self.gb_pb_sell_volume_row_minus_4 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_minus_4.setGeometry(QtCore.QRect(180, 60, 31, 23))
        self.gb_pb_sell_volume_row_minus_4.setObjectName(_fromUtf8("gb_pb_sell_volume_row_minus_4"))
        self.gb_pb_s5_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_s5_volume.setGeometry(QtCore.QRect(110, 40, 71, 20))
        self.gb_pb_s5_volume.setFlat(True)
        self.gb_pb_s5_volume.setObjectName(_fromUtf8("gb_pb_s5_volume"))
        self.gb_cb_etfCode = QtGui.QComboBox(GroupBox)
        self.gb_cb_etfCode.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.gb_cb_etfCode.setObjectName(_fromUtf8("gb_cb_etfCode"))
        self.gb_pb_s1_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_s1_volume.setGeometry(QtCore.QRect(110, 120, 71, 20))
        self.gb_pb_s1_volume.setFlat(True)
        self.gb_pb_s1_volume.setObjectName(_fromUtf8("gb_pb_s1_volume"))
        self.gb_pb_buy_volume_row_minus_4 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_minus_4.setGeometry(QtCore.QRect(180, 220, 31, 23))
        self.gb_pb_buy_volume_row_minus_4.setObjectName(_fromUtf8("gb_pb_buy_volume_row_minus_4"))
        self.gb_pb_buy_volume_row_minus_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_minus_3.setGeometry(QtCore.QRect(180, 200, 31, 23))
        self.gb_pb_buy_volume_row_minus_3.setObjectName(_fromUtf8("gb_pb_buy_volume_row_minus_3"))
        self.gb_pb_buy_volume_row_minus_5 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_minus_5.setGeometry(QtCore.QRect(180, 240, 31, 23))
        self.gb_pb_buy_volume_row_minus_5.setObjectName(_fromUtf8("gb_pb_buy_volume_row_minus_5"))
        self.gb_pb_sell_volume_5_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_5_3.setGeometry(QtCore.QRect(350, 40, 41, 23))
        self.gb_pb_sell_volume_5_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_5_3.setObjectName(_fromUtf8("gb_pb_sell_volume_5_3"))
        self.gb_pb_b5_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_b5_volume.setGeometry(QtCore.QRect(110, 240, 71, 20))
        self.gb_pb_b5_volume.setFlat(True)
        self.gb_pb_b5_volume.setObjectName(_fromUtf8("gb_pb_b5_volume"))
        self.gb_pb_b2_volume = QtGui.QPushButton(GroupBox)
        self.gb_pb_b2_volume.setGeometry(QtCore.QRect(110, 180, 71, 20))
        self.gb_pb_b2_volume.setFlat(True)
        self.gb_pb_b2_volume.setObjectName(_fromUtf8("gb_pb_b2_volume"))
        self.gb_pb_s1_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_s1_price.setGeometry(QtCore.QRect(50, 120, 61, 20))
        self.gb_pb_s1_price.setStyleSheet(_fromUtf8(""))
        self.gb_pb_s1_price.setFlat(True)
        self.gb_pb_s1_price.setObjectName(_fromUtf8("gb_pb_s1_price"))
        self.gb_pb_s3_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_s3_price.setGeometry(QtCore.QRect(50, 80, 61, 20))
        self.gb_pb_s3_price.setFlat(True)
        self.gb_pb_s3_price.setObjectName(_fromUtf8("gb_pb_s3_price"))
        self.gb_pb_b5 = QtGui.QPushButton(GroupBox)
        self.gb_pb_b5.setGeometry(QtCore.QRect(10, 240, 41, 20))
        self.gb_pb_b5.setFlat(True)
        self.gb_pb_b5.setObjectName(_fromUtf8("gb_pb_b5"))
        self.gb_pb_sell_volume_row_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_1.setGeometry(QtCore.QRect(210, 120, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_row_1.setFont(font)
        self.gb_pb_sell_volume_row_1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_row_1.setText(_fromUtf8(""))
        self.gb_pb_sell_volume_row_1.setFlat(True)
        self.gb_pb_sell_volume_row_1.setObjectName(_fromUtf8("gb_pb_sell_volume_row_1"))
        self.gb_pb_sell_volume_row_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_3.setGeometry(QtCore.QRect(210, 80, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_sell_volume_row_3.setFont(font)
        self.gb_pb_sell_volume_row_3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.gb_pb_sell_volume_row_3.setText(_fromUtf8(""))
        self.gb_pb_sell_volume_row_3.setFlat(True)
        self.gb_pb_sell_volume_row_3.setObjectName(_fromUtf8("gb_pb_sell_volume_row_3"))
        self.label_1 = QtGui.QLabel(GroupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 140, 381, 20))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gb_pb_buy_volume_row_5 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_row_5.setGeometry(QtCore.QRect(210, 240, 31, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(8)
        self.gb_pb_buy_volume_row_5.setFont(font)
        self.gb_pb_buy_volume_row_5.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.gb_pb_buy_volume_row_5.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_row_5.setFlat(True)
        self.gb_pb_buy_volume_row_5.setObjectName(_fromUtf8("gb_pb_buy_volume_row_5"))
        self.gb_pb_s5_price = QtGui.QPushButton(GroupBox)
        self.gb_pb_s5_price.setGeometry(QtCore.QRect(50, 40, 61, 20))
        self.gb_pb_s5_price.setFlat(True)
        self.gb_pb_s5_price.setObjectName(_fromUtf8("gb_pb_s5_price"))
        self.gb_pb_sell_volume_row_minus_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_row_minus_1.setGeometry(QtCore.QRect(180, 120, 31, 23))
        self.gb_pb_sell_volume_row_minus_1.setObjectName(_fromUtf8("gb_pb_sell_volume_row_minus_1"))
        self.gb_pb_sell_volume_4_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_4_1.setGeometry(QtCore.QRect(270, 60, 41, 23))
        self.gb_pb_sell_volume_4_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_4_1.setObjectName(_fromUtf8("gb_pb_sell_volume_4_1"))
        self.gb_pb_sell_volume_3_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_3_1.setGeometry(QtCore.QRect(270, 80, 41, 23))
        self.gb_pb_sell_volume_3_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_3_1.setObjectName(_fromUtf8("gb_pb_sell_volume_3_1"))
        self.gb_pb_sell_volume_2_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_2_1.setGeometry(QtCore.QRect(270, 100, 41, 23))
        self.gb_pb_sell_volume_2_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_2_1.setObjectName(_fromUtf8("gb_pb_sell_volume_2_1"))
        self.gb_pb_sell_volume_1_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_1_1.setGeometry(QtCore.QRect(270, 120, 41, 23))
        self.gb_pb_sell_volume_1_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_1_1.setObjectName(_fromUtf8("gb_pb_sell_volume_1_1"))
        self.gb_pb_sell_volume_4_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_4_2.setGeometry(QtCore.QRect(310, 60, 41, 23))
        self.gb_pb_sell_volume_4_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_4_2.setObjectName(_fromUtf8("gb_pb_sell_volume_4_2"))
        self.gb_pb_sell_volume_3_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_3_2.setGeometry(QtCore.QRect(310, 80, 41, 23))
        self.gb_pb_sell_volume_3_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_3_2.setObjectName(_fromUtf8("gb_pb_sell_volume_3_2"))
        self.gb_pb_sell_volume_2_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_2_2.setGeometry(QtCore.QRect(310, 100, 41, 23))
        self.gb_pb_sell_volume_2_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_2_2.setObjectName(_fromUtf8("gb_pb_sell_volume_2_2"))
        self.gb_pb_sell_volume_1_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_1_2.setGeometry(QtCore.QRect(310, 120, 41, 23))
        self.gb_pb_sell_volume_1_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_1_2.setObjectName(_fromUtf8("gb_pb_sell_volume_1_2"))
        self.gb_pb_sell_volume_4_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_4_3.setGeometry(QtCore.QRect(350, 60, 41, 23))
        self.gb_pb_sell_volume_4_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_4_3.setObjectName(_fromUtf8("gb_pb_sell_volume_4_3"))
        self.gb_pb_sell_volume_3_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_3_3.setGeometry(QtCore.QRect(350, 80, 41, 23))
        self.gb_pb_sell_volume_3_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_3_3.setObjectName(_fromUtf8("gb_pb_sell_volume_3_3"))
        self.gb_pb_sell_volume_2_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_2_3.setGeometry(QtCore.QRect(350, 100, 41, 23))
        self.gb_pb_sell_volume_2_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_2_3.setObjectName(_fromUtf8("gb_pb_sell_volume_2_3"))
        self.gb_pb_sell_volume_1_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_sell_volume_1_3.setGeometry(QtCore.QRect(350, 120, 41, 23))
        self.gb_pb_sell_volume_1_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF; background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(1, 150, 25); } QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_sell_volume_1_3.setObjectName(_fromUtf8("gb_pb_sell_volume_1_3"))
        self.gb_pb_buy_volume_2_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_2_1.setGeometry(QtCore.QRect(270, 180, 41, 23))
        self.gb_pb_buy_volume_2_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_2_1.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_2_1.setObjectName(_fromUtf8("gb_pb_buy_volume_2_1"))
        self.gb_pb_buy_volume_3_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_3_1.setGeometry(QtCore.QRect(270, 200, 41, 23))
        self.gb_pb_buy_volume_3_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_3_1.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_3_1.setObjectName(_fromUtf8("gb_pb_buy_volume_3_1"))
        self.gb_pb_buy_volume_4_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_4_1.setGeometry(QtCore.QRect(270, 220, 41, 23))
        self.gb_pb_buy_volume_4_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_4_1.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_4_1.setObjectName(_fromUtf8("gb_pb_buy_volume_4_1"))
        self.gb_pb_buy_volume_5_1 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_5_1.setGeometry(QtCore.QRect(270, 240, 41, 23))
        self.gb_pb_buy_volume_5_1.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_5_1.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_5_1.setObjectName(_fromUtf8("gb_pb_buy_volume_5_1"))
        self.gb_pb_buy_volume_2_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_2_2.setGeometry(QtCore.QRect(310, 180, 41, 23))
        self.gb_pb_buy_volume_2_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_2_2.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_2_2.setObjectName(_fromUtf8("gb_pb_buy_volume_2_2"))
        self.gb_pb_buy_volume_3_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_3_2.setGeometry(QtCore.QRect(310, 200, 41, 23))
        self.gb_pb_buy_volume_3_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_3_2.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_3_2.setObjectName(_fromUtf8("gb_pb_buy_volume_3_2"))
        self.gb_pb_buy_volume_4_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_4_2.setGeometry(QtCore.QRect(310, 220, 41, 23))
        self.gb_pb_buy_volume_4_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_4_2.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_4_2.setObjectName(_fromUtf8("gb_pb_buy_volume_4_2"))
        self.gb_pb_buy_volume_5_2 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_5_2.setGeometry(QtCore.QRect(310, 240, 41, 23))
        self.gb_pb_buy_volume_5_2.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_5_2.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_5_2.setObjectName(_fromUtf8("gb_pb_buy_volume_5_2"))
        self.gb_pb_buy_volume_2_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_2_3.setGeometry(QtCore.QRect(350, 180, 41, 23))
        self.gb_pb_buy_volume_2_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_2_3.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_2_3.setObjectName(_fromUtf8("gb_pb_buy_volume_2_3"))
        self.gb_pb_buy_volume_3_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_3_3.setGeometry(QtCore.QRect(350, 200, 41, 23))
        self.gb_pb_buy_volume_3_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_3_3.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_3_3.setObjectName(_fromUtf8("gb_pb_buy_volume_3_3"))
        self.gb_pb_buy_volume_4_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_4_3.setGeometry(QtCore.QRect(350, 220, 41, 23))
        self.gb_pb_buy_volume_4_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_4_3.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_4_3.setObjectName(_fromUtf8("gb_pb_buy_volume_4_3"))
        self.gb_pb_buy_volume_5_3 = QtGui.QPushButton(GroupBox)
        self.gb_pb_buy_volume_5_3.setGeometry(QtCore.QRect(350, 240, 41, 23))
        self.gb_pb_buy_volume_5_3.setStyleSheet(_fromUtf8("QPushButton {border: 1px solid #FFFFFF;background-color: rgb(189, 189, 189);border-radius: 3px; color: rgb(255, 0, 0); }\n"
"QPushButton:hover { background-color: rgb(255, 255, 255); }"))
        self.gb_pb_buy_volume_5_3.setText(_fromUtf8(""))
        self.gb_pb_buy_volume_5_3.setObjectName(_fromUtf8("gb_pb_buy_volume_5_3"))

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox", None))
        self.gb_pb_b1_volume.setText(_translate("GroupBox", "买1", None))
        self.gb_pb_buy_volume_row_3.setText(_translate("GroupBox", "500", None))
        self.gb_pb_sell_volume_total_minus.setText(_translate("GroupBox", "-", None))
        self.gb_pb_s2.setText(_translate("GroupBox", "卖2", None))
        self.gb_pb_sell_volume_column_2.setText(_translate("GroupBox", "100", None))
        self.gb_pb_sell_volume_5_2.setText(_translate("GroupBox", "300", None))
        self.gb_pb_b1_price.setText(_translate("GroupBox", "买1", None))
        self.gb_pb_sell_volume_row_minus_5.setText(_translate("GroupBox", "-", None))
        self.gb_pb_s5.setText(_translate("GroupBox", "卖5", None))
        self.gb_pb_buy_volume_row_minus_1.setText(_translate("GroupBox", "-", None))
        self.gb_pb_b1.setText(_translate("GroupBox", "买1", None))
        self.gb_pb_b4_price.setText(_translate("GroupBox", "买4", None))
        self.gb_pb_b2.setText(_translate("GroupBox", "买2", None))
        self.gb_pb_buy_volume_total_minus.setText(_translate("GroupBox", "-", None))
        self.gb_pb_b3_price.setText(_translate("GroupBox", "买3", None))
        self.gb_pb_sell_total_money.setText(_translate("GroupBox", "1,123万元", None))
        self.gb_pb_b5_price.setText(_translate("GroupBox", "买5", None))
        self.gb_pb_buy_total_money.setText(_translate("GroupBox", "1,123万元", None))
        self.gb_pb_sell_volume_5_1.setText(_translate("GroupBox", "200", None))
        self.gb_pb_s4.setText(_translate("GroupBox", "卖4", None))
        self.gb_pb_buy_volume_column_1.setText(_translate("GroupBox", "120", None))
        self.gb_pb_b2_price.setText(_translate("GroupBox", "买2", None))
        self.gb_pb_s2_volume.setText(_translate("GroupBox", "卖2", None))
        self.gb_pb_s1.setText(_translate("GroupBox", "卖1", None))
        self.gb_pb_b3.setText(_translate("GroupBox", "买3", None))
        self.gb_pb_sell_volume_column_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_s4_price.setText(_translate("GroupBox", "卖4", None))
        self.gb_pb_s2_price.setText(_translate("GroupBox", "卖2", None))
        self.gb_pb_buy_volume_row_minus_2.setText(_translate("GroupBox", "-", None))
        self.gb_pb_sell_volume_column_1.setText(_translate("GroupBox", "120", None))
        self.gb_pb_sell_volume_total.setText(_translate("GroupBox", "720", None))
        self.gb_pb_buy_volume_total.setText(_translate("GroupBox", "720", None))
        self.gb_pb_buy_volume_column_2.setText(_translate("GroupBox", "100", None))
        self.gb_pb_sell_volume_row_5.setText(_translate("GroupBox", "500", None))
        self.gb_pb_b3_volume.setText(_translate("GroupBox", "买3", None))
        self.gb_pb_sell_volume_row_minus_2.setText(_translate("GroupBox", "-", None))
        self.gb_pb_s3.setText(_translate("GroupBox", "卖3", None))
        self.gb_pb_s3_volume.setText(_translate("GroupBox", "卖3", None))
        self.gb_pb_sell_volume_row_minus_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_buy_volume_column_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_b4_volume.setText(_translate("GroupBox", "买4", None))
        self.gb_pb_s4_volume.setText(_translate("GroupBox", "卖4", None))
        self.gb_pb_b4.setText(_translate("GroupBox", "买4", None))
        self.gb_pb_sell_volume_row_minus_4.setText(_translate("GroupBox", "-", None))
        self.gb_pb_s5_volume.setText(_translate("GroupBox", "卖5", None))
        self.gb_pb_s1_volume.setText(_translate("GroupBox", "卖1", None))
        self.gb_pb_buy_volume_row_minus_4.setText(_translate("GroupBox", "-", None))
        self.gb_pb_buy_volume_row_minus_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_buy_volume_row_minus_5.setText(_translate("GroupBox", "-", None))
        self.gb_pb_sell_volume_5_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_b5_volume.setText(_translate("GroupBox", "买5", None))
        self.gb_pb_b2_volume.setText(_translate("GroupBox", "买2", None))
        self.gb_pb_s1_price.setText(_translate("GroupBox", "卖1", None))
        self.gb_pb_s3_price.setText(_translate("GroupBox", "卖3", None))
        self.gb_pb_b5.setText(_translate("GroupBox", "买5", None))
        self.label_1.setText(_translate("GroupBox", "---------------------------------------------------------------", None))
        self.gb_pb_s5_price.setText(_translate("GroupBox", "卖5", None))
        self.gb_pb_sell_volume_row_minus_1.setText(_translate("GroupBox", "-", None))
        self.gb_pb_sell_volume_4_1.setText(_translate("GroupBox", "200", None))
        self.gb_pb_sell_volume_3_1.setText(_translate("GroupBox", "200", None))
        self.gb_pb_sell_volume_2_1.setText(_translate("GroupBox", "200", None))
        self.gb_pb_sell_volume_1_1.setText(_translate("GroupBox", "200", None))
        self.gb_pb_sell_volume_4_2.setText(_translate("GroupBox", "300", None))
        self.gb_pb_sell_volume_3_2.setText(_translate("GroupBox", "300", None))
        self.gb_pb_sell_volume_2_2.setText(_translate("GroupBox", "300", None))
        self.gb_pb_sell_volume_1_2.setText(_translate("GroupBox", "300", None))
        self.gb_pb_sell_volume_4_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_sell_volume_3_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_sell_volume_2_3.setText(_translate("GroupBox", "-", None))
        self.gb_pb_sell_volume_1_3.setText(_translate("GroupBox", "-", None))

