# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(949, 641)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("QWidget#centralwidget{border-width:1px;border-style:solid;border-color:#87CEFA}"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_set = QtGui.QMenu(self.menubar)
        self.menu_set.setObjectName(_fromUtf8("menu_set"))
        self.menu_view = QtGui.QMenu(self.menubar)
        self.menu_view.setObjectName(_fromUtf8("menu_view"))
        self.menu_stock = QtGui.QMenu(self.menubar)
        self.menu_stock.setObjectName(_fromUtf8("menu_stock"))
        self.menu_future = QtGui.QMenu(self.menubar)
        self.menu_future.setObjectName(_fromUtf8("menu_future"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        MainWindow.setMenuBar(self.menubar)
        self.toolbar_key = QtGui.QToolBar(MainWindow)
        self.toolbar_key.setFloatable(False)
        self.toolbar_key.setObjectName(_fromUtf8("toolbar_key"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar_key)
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_load = QtGui.QAction(MainWindow)
        self.action_load.setObjectName(_fromUtf8("action_load"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_change_at = QtGui.QAction(MainWindow)
        self.action_change_at.setObjectName(_fromUtf8("action_change_at"))
        self.action_set_key = QtGui.QAction(MainWindow)
        self.action_set_key.setObjectName(_fromUtf8("action_set_key"))
        self.action_cash = QtGui.QAction(MainWindow)
        self.action_cash.setObjectName(_fromUtf8("action_cash"))
        self.action_s_quick_ss = QtGui.QAction(MainWindow)
        self.action_s_quick_ss.setObjectName(_fromUtf8("action_s_quick_ss"))
        self.action_s_trade = QtGui.QAction(MainWindow)
        self.action_s_trade.setObjectName(_fromUtf8("action_s_trade"))
        self.action_s_basket = QtGui.QAction(MainWindow)
        self.action_s_basket.setObjectName(_fromUtf8("action_s_basket"))
        self.action_s_orders = QtGui.QAction(MainWindow)
        self.action_s_orders.setObjectName(_fromUtf8("action_s_orders"))
        self.action_s_order_collect = QtGui.QAction(MainWindow)
        self.action_s_order_collect.setObjectName(_fromUtf8("action_s_order_collect"))
        self.action_s_position = QtGui.QAction(MainWindow)
        self.action_s_position.setObjectName(_fromUtf8("action_s_position"))
        self.action_s_easy_deal = QtGui.QAction(MainWindow)
        self.action_s_easy_deal.setObjectName(_fromUtf8("action_s_easy_deal"))
        self.action_s_deal = QtGui.QAction(MainWindow)
        self.action_s_deal.setObjectName(_fromUtf8("action_s_deal"))
        self.action_strfund = QtGui.QAction(MainWindow)
        self.action_strfund.setObjectName(_fromUtf8("action_strfund"))
        self.action_f_trade = QtGui.QAction(MainWindow)
        self.action_f_trade.setObjectName(_fromUtf8("action_f_trade"))
        self.action_f_orders = QtGui.QAction(MainWindow)
        self.action_f_orders.setObjectName(_fromUtf8("action_f_orders"))
        self.action_f_position = QtGui.QAction(MainWindow)
        self.action_f_position.setObjectName(_fromUtf8("action_f_position"))
        self.action_f_deal = QtGui.QAction(MainWindow)
        self.action_f_deal.setObjectName(_fromUtf8("action_f_deal"))
        self.action_doc = QtGui.QAction(MainWindow)
        self.action_doc.setObjectName(_fromUtf8("action_doc"))
        self.action_key_0 = QtGui.QAction(MainWindow)
        self.action_key_0.setObjectName(_fromUtf8("action_key_0"))
        self.action_key_1 = QtGui.QAction(MainWindow)
        self.action_key_1.setObjectName(_fromUtf8("action_key_1"))
        self.action_key_2 = QtGui.QAction(MainWindow)
        self.action_key_2.setObjectName(_fromUtf8("action_key_2"))
        self.action_key_3 = QtGui.QAction(MainWindow)
        self.action_key_3.setObjectName(_fromUtf8("action_key_3"))
        self.action_key_4 = QtGui.QAction(MainWindow)
        self.action_key_4.setObjectName(_fromUtf8("action_key_4"))
        self.action_key_5 = QtGui.QAction(MainWindow)
        self.action_key_5.setObjectName(_fromUtf8("action_key_5"))
        self.action_key_6 = QtGui.QAction(MainWindow)
        self.action_key_6.setObjectName(_fromUtf8("action_key_6"))
        self.action_key_7 = QtGui.QAction(MainWindow)
        self.action_key_7.setObjectName(_fromUtf8("action_key_7"))
        self.action_key_8 = QtGui.QAction(MainWindow)
        self.action_key_8.setObjectName(_fromUtf8("action_key_8"))
        self.action_key_9 = QtGui.QAction(MainWindow)
        self.action_key_9.setObjectName(_fromUtf8("action_key_9"))
        self.action_key_10 = QtGui.QAction(MainWindow)
        self.action_key_10.setObjectName(_fromUtf8("action_key_10"))
        self.action_key_11 = QtGui.QAction(MainWindow)
        self.action_key_11.setObjectName(_fromUtf8("action_key_11"))
        self.action_key_12 = QtGui.QAction(MainWindow)
        self.action_key_12.setObjectName(_fromUtf8("action_key_12"))
        self.action_key_13 = QtGui.QAction(MainWindow)
        self.action_key_13.setObjectName(_fromUtf8("action_key_13"))
        self.action_key_plus = QtGui.QAction(MainWindow)
        self.action_key_plus.setObjectName(_fromUtf8("action_key_plus"))
        self.action_deposit = QtGui.QAction(MainWindow)
        self.action_deposit.setObjectName(_fromUtf8("action_deposit"))
        self.action_key_14 = QtGui.QAction(MainWindow)
        self.action_key_14.setObjectName(_fromUtf8("action_key_14"))
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_load)
        self.menu_file.addAction(self.action_exit)
        self.menu_set.addAction(self.action_change_at)
        self.menu_set.addAction(self.action_set_key)
        self.menu_view.addAction(self.action_cash)
        self.menu_view.addAction(self.action_deposit)
        self.menu_stock.addAction(self.action_s_quick_ss)
        self.menu_stock.addAction(self.action_s_trade)
        self.menu_stock.addAction(self.action_s_basket)
        self.menu_stock.addSeparator()
        self.menu_stock.addSeparator()
        self.menu_stock.addAction(self.action_s_orders)
        self.menu_stock.addAction(self.action_s_order_collect)
        self.menu_stock.addSeparator()
        self.menu_stock.addSeparator()
        self.menu_stock.addAction(self.action_s_position)
        self.menu_stock.addSeparator()
        self.menu_stock.addSeparator()
        self.menu_stock.addAction(self.action_s_easy_deal)
        self.menu_stock.addAction(self.action_s_deal)
        self.menu_stock.addSeparator()
        self.menu_stock.addSeparator()
        self.menu_stock.addAction(self.action_strfund)
        self.menu_future.addAction(self.action_f_trade)
        self.menu_future.addAction(self.action_f_orders)
        self.menu_future.addAction(self.action_f_position)
        self.menu_future.addAction(self.action_f_deal)
        self.menu_help.addAction(self.action_doc)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_set.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_stock.menuAction())
        self.menubar.addAction(self.menu_future.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.toolbar_key.addAction(self.action_key_0)
        self.toolbar_key.addAction(self.action_key_1)
        self.toolbar_key.addAction(self.action_key_2)
        self.toolbar_key.addAction(self.action_key_3)
        self.toolbar_key.addAction(self.action_key_4)
        self.toolbar_key.addAction(self.action_key_5)
        self.toolbar_key.addAction(self.action_key_6)
        self.toolbar_key.addAction(self.action_key_7)
        self.toolbar_key.addAction(self.action_key_8)
        self.toolbar_key.addAction(self.action_key_9)
        self.toolbar_key.addAction(self.action_key_10)
        self.toolbar_key.addAction(self.action_key_11)
        self.toolbar_key.addAction(self.action_key_12)
        self.toolbar_key.addAction(self.action_key_13)
        self.toolbar_key.addAction(self.action_key_14)
        self.toolbar_key.addAction(self.action_key_plus)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MTClient", None))
        self.menu_file.setTitle(_translate("MainWindow", "文件", None))
        self.menu_set.setTitle(_translate("MainWindow", "设置", None))
        self.menu_view.setTitle(_translate("MainWindow", "视图", None))
        self.menu_stock.setTitle(_translate("MainWindow", "现货", None))
        self.menu_future.setTitle(_translate("MainWindow", "期货", None))
        self.menu_help.setTitle(_translate("MainWindow", "帮助", None))
        self.toolbar_key.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_save.setText(_translate("MainWindow", "保存布局", None))
        self.action_load.setText(_translate("MainWindow", "载入布局", None))
        self.action_exit.setText(_translate("MainWindow", "退出", None))
        self.action_change_at.setText(_translate("MainWindow", "切换产品账户", None))
        self.action_set_key.setText(_translate("MainWindow", "自定义快捷键", None))
        self.action_cash.setText(_translate("MainWindow", "头寸监控", None))
        self.action_s_quick_ss.setText(_translate("MainWindow", "快速申赎", None))
        self.action_s_trade.setText(_translate("MainWindow", "股票买卖", None))
        self.action_s_basket.setText(_translate("MainWindow", "篮子买卖", None))
        self.action_s_orders.setText(_translate("MainWindow", "委托列表", None))
        self.action_s_order_collect.setText(_translate("MainWindow", "委托汇总", None))
        self.action_s_position.setText(_translate("MainWindow", "现货持仓", None))
        self.action_s_easy_deal.setText(_translate("MainWindow", "简版成交明细", None))
        self.action_s_deal.setText(_translate("MainWindow", "完整成交明细", None))
        self.action_strfund.setText(_translate("MainWindow", "分级基金", None))
        self.action_f_trade.setText(_translate("MainWindow", "期货买卖", None))
        self.action_f_orders.setText(_translate("MainWindow", "期货委托列表", None))
        self.action_f_position.setText(_translate("MainWindow", "期货持仓", None))
        self.action_f_deal.setText(_translate("MainWindow", "期货成交明细", None))
        self.action_doc.setText(_translate("MainWindow", "帮助文档", None))
        self.action_key_0.setText(_translate("MainWindow", "0", None))
        self.action_key_1.setText(_translate("MainWindow", "1", None))
        self.action_key_2.setText(_translate("MainWindow", "2", None))
        self.action_key_3.setText(_translate("MainWindow", "3", None))
        self.action_key_4.setText(_translate("MainWindow", "4", None))
        self.action_key_5.setText(_translate("MainWindow", "5", None))
        self.action_key_6.setText(_translate("MainWindow", "6", None))
        self.action_key_7.setText(_translate("MainWindow", "7", None))
        self.action_key_8.setText(_translate("MainWindow", "8", None))
        self.action_key_9.setText(_translate("MainWindow", "9", None))
        self.action_key_10.setText(_translate("MainWindow", "10", None))
        self.action_key_11.setText(_translate("MainWindow", "11", None))
        self.action_key_12.setText(_translate("MainWindow", "12", None))
        self.action_key_13.setText(_translate("MainWindow", "13", None))
        self.action_key_plus.setText(_translate("MainWindow", "+", None))
        self.action_deposit.setText(_translate("MainWindow", "今保证金", None))
        self.action_key_14.setText(_translate("MainWindow", "14", None))

