# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpeedApplyRedeem.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SpeedApplyRedeem(object):
    def setupUi(self, SpeedApplyRedeem):
        SpeedApplyRedeem.setObjectName(_fromUtf8("SpeedApplyRedeem"))
        SpeedApplyRedeem.resize(792, 351)
        SpeedApplyRedeem.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        SpeedApplyRedeem.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dw_SpeedApplyRedeem = QtGui.QWidget()
        self.dw_SpeedApplyRedeem.setObjectName(_fromUtf8("dw_SpeedApplyRedeem"))
        self.groupBox = QtGui.QGroupBox(self.dw_SpeedApplyRedeem)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 311))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pb_s1_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s1_volume.setGeometry(QtCore.QRect(120, 100, 61, 21))
        self.pb_s1_volume.setText(_fromUtf8(""))
        self.pb_s1_volume.setFlat(True)
        self.pb_s1_volume.setObjectName(_fromUtf8("pb_s1_volume"))
        self.pb_s3_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s3_volume.setGeometry(QtCore.QRect(120, 60, 61, 21))
        self.pb_s3_volume.setText(_fromUtf8(""))
        self.pb_s3_volume.setFlat(True)
        self.pb_s3_volume.setObjectName(_fromUtf8("pb_s3_volume"))
        self.pb_s2_price = QtGui.QPushButton(self.groupBox)
        self.pb_s2_price.setGeometry(QtCore.QRect(60, 80, 61, 21))
        self.pb_s2_price.setStyleSheet(_fromUtf8("\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.pb_s2_price.setText(_fromUtf8(""))
        self.pb_s2_price.setFlat(True)
        self.pb_s2_price.setObjectName(_fromUtf8("pb_s2_price"))
        self.pb_s5_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s5_volume.setGeometry(QtCore.QRect(120, 20, 61, 21))
        self.pb_s5_volume.setText(_fromUtf8(""))
        self.pb_s5_volume.setFlat(True)
        self.pb_s5_volume.setObjectName(_fromUtf8("pb_s5_volume"))
        self.pb_s4_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s4_volume.setGeometry(QtCore.QRect(120, 40, 61, 21))
        self.pb_s4_volume.setText(_fromUtf8(""))
        self.pb_s4_volume.setFlat(True)
        self.pb_s4_volume.setObjectName(_fromUtf8("pb_s4_volume"))
        self.pb_s5_price = QtGui.QPushButton(self.groupBox)
        self.pb_s5_price.setGeometry(QtCore.QRect(60, 20, 61, 21))
        self.pb_s5_price.setText(_fromUtf8(""))
        self.pb_s5_price.setFlat(True)
        self.pb_s5_price.setObjectName(_fromUtf8("pb_s5_price"))
        self.pb_s1_price = QtGui.QPushButton(self.groupBox)
        self.pb_s1_price.setGeometry(QtCore.QRect(60, 100, 61, 21))
        self.pb_s1_price.setStyleSheet(_fromUtf8(""))
        self.pb_s1_price.setText(_fromUtf8(""))
        self.pb_s1_price.setFlat(True)
        self.pb_s1_price.setObjectName(_fromUtf8("pb_s1_price"))
        self.pb_s3_price = QtGui.QPushButton(self.groupBox)
        self.pb_s3_price.setGeometry(QtCore.QRect(60, 60, 61, 21))
        self.pb_s3_price.setText(_fromUtf8(""))
        self.pb_s3_price.setFlat(True)
        self.pb_s3_price.setObjectName(_fromUtf8("pb_s3_price"))
        self.pb_s4_price = QtGui.QPushButton(self.groupBox)
        self.pb_s4_price.setGeometry(QtCore.QRect(60, 40, 61, 21))
        self.pb_s4_price.setText(_fromUtf8(""))
        self.pb_s4_price.setFlat(True)
        self.pb_s4_price.setObjectName(_fromUtf8("pb_s4_price"))
        self.pb_s2_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s2_volume.setGeometry(QtCore.QRect(120, 80, 61, 21))
        self.pb_s2_volume.setText(_fromUtf8(""))
        self.pb_s2_volume.setFlat(True)
        self.pb_s2_volume.setObjectName(_fromUtf8("pb_s2_volume"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(0, 120, 281, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.pb_b5_price = QtGui.QPushButton(self.groupBox)
        self.pb_b5_price.setGeometry(QtCore.QRect(60, 280, 61, 21))
        self.pb_b5_price.setText(_fromUtf8(""))
        self.pb_b5_price.setFlat(True)
        self.pb_b5_price.setObjectName(_fromUtf8("pb_b5_price"))
        self.pb_b5_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b5_volume.setGeometry(QtCore.QRect(120, 280, 61, 21))
        self.pb_b5_volume.setText(_fromUtf8(""))
        self.pb_b5_volume.setFlat(True)
        self.pb_b5_volume.setObjectName(_fromUtf8("pb_b5_volume"))
        self.pb_b3_price = QtGui.QPushButton(self.groupBox)
        self.pb_b3_price.setGeometry(QtCore.QRect(60, 240, 61, 21))
        self.pb_b3_price.setText(_fromUtf8(""))
        self.pb_b3_price.setFlat(True)
        self.pb_b3_price.setObjectName(_fromUtf8("pb_b3_price"))
        self.pb_b2_price = QtGui.QPushButton(self.groupBox)
        self.pb_b2_price.setGeometry(QtCore.QRect(60, 220, 61, 21))
        self.pb_b2_price.setText(_fromUtf8(""))
        self.pb_b2_price.setFlat(True)
        self.pb_b2_price.setObjectName(_fromUtf8("pb_b2_price"))
        self.pb_b1_price = QtGui.QPushButton(self.groupBox)
        self.pb_b1_price.setGeometry(QtCore.QRect(60, 200, 61, 21))
        self.pb_b1_price.setText(_fromUtf8(""))
        self.pb_b1_price.setFlat(True)
        self.pb_b1_price.setObjectName(_fromUtf8("pb_b1_price"))
        self.pb_b1_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b1_volume.setGeometry(QtCore.QRect(120, 220, 61, 21))
        self.pb_b1_volume.setText(_fromUtf8(""))
        self.pb_b1_volume.setFlat(True)
        self.pb_b1_volume.setObjectName(_fromUtf8("pb_b1_volume"))
        self.pb_b4_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b4_volume.setGeometry(QtCore.QRect(120, 260, 61, 21))
        self.pb_b4_volume.setText(_fromUtf8(""))
        self.pb_b4_volume.setFlat(True)
        self.pb_b4_volume.setObjectName(_fromUtf8("pb_b4_volume"))
        self.pb_b4_price = QtGui.QPushButton(self.groupBox)
        self.pb_b4_price.setGeometry(QtCore.QRect(60, 260, 61, 21))
        self.pb_b4_price.setText(_fromUtf8(""))
        self.pb_b4_price.setFlat(True)
        self.pb_b4_price.setObjectName(_fromUtf8("pb_b4_price"))
        self.pb_b2_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b2_volume.setGeometry(QtCore.QRect(120, 200, 61, 21))
        self.pb_b2_volume.setText(_fromUtf8(""))
        self.pb_b2_volume.setFlat(True)
        self.pb_b2_volume.setObjectName(_fromUtf8("pb_b2_volume"))
        self.pb_b3_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b3_volume.setGeometry(QtCore.QRect(120, 240, 61, 21))
        self.pb_b3_volume.setText(_fromUtf8(""))
        self.pb_b3_volume.setFlat(True)
        self.pb_b3_volume.setObjectName(_fromUtf8("pb_b3_volume"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(0, 190, 281, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 220, 51, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 240, 51, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 51, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 280, 51, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pb_info_money = QtGui.QPushButton(self.groupBox)
        self.pb_info_money.setGeometry(QtCore.QRect(190, 150, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_info_money.setFont(font)
        self.pb_info_money.setFlat(True)
        self.pb_info_money.setObjectName(_fromUtf8("pb_info_money"))
        self.pushButton_51 = QtGui.QPushButton(self.groupBox)
        self.pushButton_51.setGeometry(QtCore.QRect(10, 130, 51, 20))
        self.pushButton_51.setFlat(True)
        self.pushButton_51.setObjectName(_fromUtf8("pushButton_51"))
        self.pushButton_49 = QtGui.QPushButton(self.groupBox)
        self.pushButton_49.setGeometry(QtCore.QRect(60, 130, 61, 20))
        self.pushButton_49.setFlat(True)
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.pushButton_52 = QtGui.QPushButton(self.groupBox)
        self.pushButton_52.setGeometry(QtCore.QRect(60, 170, 61, 20))
        self.pushButton_52.setFlat(True)
        self.pushButton_52.setObjectName(_fromUtf8("pushButton_52"))
        self.pushButton_46 = QtGui.QPushButton(self.groupBox)
        self.pushButton_46.setGeometry(QtCore.QRect(10, 170, 51, 20))
        self.pushButton_46.setFlat(True)
        self.pushButton_46.setObjectName(_fromUtf8("pushButton_46"))
        self.pushButton_45 = QtGui.QPushButton(self.groupBox)
        self.pushButton_45.setGeometry(QtCore.QRect(60, 150, 61, 20))
        self.pushButton_45.setFlat(True)
        self.pushButton_45.setObjectName(_fromUtf8("pushButton_45"))
        self.pushButton_41 = QtGui.QPushButton(self.groupBox)
        self.pushButton_41.setGeometry(QtCore.QRect(10, 150, 51, 20))
        self.pushButton_41.setFlat(True)
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.pb_b_money = QtGui.QPushButton(self.groupBox)
        self.pb_b_money.setGeometry(QtCore.QRect(190, 240, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_b_money.setFont(font)
        self.pb_b_money.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); }\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
" "))
        self.pb_b_money.setFlat(True)
        self.pb_b_money.setObjectName(_fromUtf8("pb_b_money"))
        self.pb_s_money = QtGui.QPushButton(self.groupBox)
        self.pb_s_money.setGeometry(QtCore.QRect(190, 60, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_s_money.setFont(font)
        self.pb_s_money.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 85, 0); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.pb_s_money.setFlat(True)
        self.pb_s_money.setObjectName(_fromUtf8("pb_s_money"))
        self.pb_s_mins = QtGui.QPushButton(self.groupBox)
        self.pb_s_mins.setGeometry(QtCore.QRect(190, 100, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_s_mins.setFont(font)
        self.pb_s_mins.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 85, 0); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.pb_s_mins.setFlat(True)
        self.pb_s_mins.setObjectName(_fromUtf8("pb_s_mins"))
        self.pb_b_maxb = QtGui.QPushButton(self.groupBox)
        self.pb_b_maxb.setGeometry(QtCore.QRect(190, 200, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_b_maxb.setFont(font)
        self.pb_b_maxb.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.pb_b_maxb.setFlat(True)
        self.pb_b_maxb.setObjectName(_fromUtf8("pb_b_maxb"))
        self.groupBox_2 = QtGui.QGroupBox(self.dw_SpeedApplyRedeem)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 481, 311))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.l_orderPrice_2 = QtGui.QLabel(self.groupBox_2)
        self.l_orderPrice_2.setGeometry(QtCore.QRect(190, 30, 54, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_orderPrice_2.sizePolicy().hasHeightForWidth())
        self.l_orderPrice_2.setSizePolicy(sizePolicy)
        self.l_orderPrice_2.setObjectName(_fromUtf8("l_orderPrice_2"))
        self.l_orderVolume_2 = QtGui.QLabel(self.groupBox_2)
        self.l_orderVolume_2.setGeometry(QtCore.QRect(20, 60, 54, 20))
        self.l_orderVolume_2.setObjectName(_fromUtf8("l_orderVolume_2"))
        self.pb_sell = QtGui.QPushButton(self.groupBox_2)
        self.pb_sell.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.pb_sell.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }\n"
""))
        self.pb_sell.setObjectName(_fromUtf8("pb_sell"))
        self.pb_buy = QtGui.QPushButton(self.groupBox_2)
        self.pb_buy.setGeometry(QtCore.QRect(200, 60, 75, 23))
        self.pb_buy.setStyleSheet(_fromUtf8("QPushButton { background-color: #FF0000}"))
        self.pb_buy.setObjectName(_fromUtf8("pb_buy"))
        self.l_stockCode = QtGui.QLabel(self.groupBox_2)
        self.l_stockCode.setGeometry(QtCore.QRect(20, 30, 54, 20))
        self.l_stockCode.setObjectName(_fromUtf8("l_stockCode"))
        self.le_stockCode = QtGui.QLineEdit(self.groupBox_2)
        self.le_stockCode.setGeometry(QtCore.QRect(80, 30, 81, 20))
        self.le_stockCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_stockCode.setObjectName(_fromUtf8("le_stockCode"))
        self.pb_useCode1 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode1.setGeometry(QtCore.QRect(80, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode1.setFont(font)
        self.pb_useCode1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode1.setFlat(True)
        self.pb_useCode1.setObjectName(_fromUtf8("pb_useCode1"))
        self.pb_useCode5 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode5.setGeometry(QtCore.QRect(280, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode5.setFont(font)
        self.pb_useCode5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode5.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode5.setFlat(True)
        self.pb_useCode5.setObjectName(_fromUtf8("pb_useCode5"))
        self.pb_useCode4 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode4.setGeometry(QtCore.QRect(230, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode4.setFont(font)
        self.pb_useCode4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode4.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode4.setFlat(True)
        self.pb_useCode4.setObjectName(_fromUtf8("pb_useCode4"))
        self.pb_useCode8 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode8.setGeometry(QtCore.QRect(430, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode8.setFont(font)
        self.pb_useCode8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode8.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
""))
        self.pb_useCode8.setFlat(True)
        self.pb_useCode8.setObjectName(_fromUtf8("pb_useCode8"))
        self.pb_useCode = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode.setGeometry(QtCore.QRect(10, 90, 71, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setUnderline(True)
        self.pb_useCode.setFont(font)
        self.pb_useCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode.setFlat(True)
        self.pb_useCode.setObjectName(_fromUtf8("pb_useCode"))
        self.pb_useCode3 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode3.setGeometry(QtCore.QRect(180, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode3.setFont(font)
        self.pb_useCode3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode3.setFlat(True)
        self.pb_useCode3.setObjectName(_fromUtf8("pb_useCode3"))
        self.pb_useCode7 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode7.setGeometry(QtCore.QRect(380, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode7.setFont(font)
        self.pb_useCode7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode7.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode7.setFlat(True)
        self.pb_useCode7.setObjectName(_fromUtf8("pb_useCode7"))
        self.pb_useCode6 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode6.setGeometry(QtCore.QRect(330, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode6.setFont(font)
        self.pb_useCode6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode6.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
"\n"
" "))
        self.pb_useCode6.setFlat(True)
        self.pb_useCode6.setObjectName(_fromUtf8("pb_useCode6"))
        self.pb_useCode2 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode2.setGeometry(QtCore.QRect(130, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode2.setFont(font)
        self.pb_useCode2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
"\n"
" "))
        self.pb_useCode2.setFlat(True)
        self.pb_useCode2.setObjectName(_fromUtf8("pb_useCode2"))
        self.pb_useMoney = QtGui.QPushButton(self.groupBox_2)
        self.pb_useMoney.setGeometry(QtCore.QRect(10, 150, 71, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setUnderline(True)
        self.pb_useMoney.setFont(font)
        self.pb_useMoney.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useMoney.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
"\n"
" "))
        self.pb_useMoney.setFlat(True)
        self.pb_useMoney.setObjectName(_fromUtf8("pb_useMoney"))
        self.pb_useVolume = QtGui.QPushButton(self.groupBox_2)
        self.pb_useVolume.setGeometry(QtCore.QRect(10, 120, 71, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setUnderline(True)
        self.pb_useVolume.setFont(font)
        self.pb_useVolume.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useVolume.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useVolume.setFlat(True)
        self.pb_useVolume.setObjectName(_fromUtf8("pb_useVolume"))
        self.l_basket = QtGui.QLabel(self.groupBox_2)
        self.l_basket.setGeometry(QtCore.QRect(350, 120, 54, 20))
        self.l_basket.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.l_basket.setObjectName(_fromUtf8("l_basket"))
        self.pb_buzhunum = QtGui.QPushButton(self.groupBox_2)
        self.pb_buzhunum.setGeometry(QtCore.QRect(280, 150, 51, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_buzhunum.setFont(font)
        self.pb_buzhunum.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_buzhunum.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_buzhunum.setFlat(True)
        self.pb_buzhunum.setObjectName(_fromUtf8("pb_buzhunum"))
        self.pb_useVolume3 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useVolume3.setGeometry(QtCore.QRect(180, 120, 51, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useVolume3.setFont(font)
        self.pb_useVolume3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useVolume3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
""))
        self.pb_useVolume3.setFlat(True)
        self.pb_useVolume3.setObjectName(_fromUtf8("pb_useVolume3"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(190, 150, 41, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.l_sellNumber = QtGui.QLabel(self.groupBox_2)
        self.l_sellNumber.setGeometry(QtCore.QRect(360, 150, 41, 30))
        self.l_sellNumber.setObjectName(_fromUtf8("l_sellNumber"))
        self.pb_useVolume2 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useVolume2.setGeometry(QtCore.QRect(130, 120, 51, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useVolume2.setFont(font)
        self.pb_useVolume2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useVolume2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useVolume2.setFlat(True)
        self.pb_useVolume2.setObjectName(_fromUtf8("pb_useVolume2"))
        self.pb_useVolume5 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useVolume5.setGeometry(QtCore.QRect(280, 120, 51, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useVolume5.setFont(font)
        self.pb_useVolume5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useVolume5.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
" "))
        self.pb_useVolume5.setFlat(True)
        self.pb_useVolume5.setObjectName(_fromUtf8("pb_useVolume5"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(240, 150, 41, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pb_basket = QtGui.QPushButton(self.groupBox_2)
        self.pb_basket.setGeometry(QtCore.QRect(410, 120, 50, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_basket.setFont(font)
        self.pb_basket.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_basket.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_basket.setFlat(True)
        self.pb_basket.setObjectName(_fromUtf8("pb_basket"))
        self.pb_useVolume1 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useVolume1.setGeometry(QtCore.QRect(80, 120, 51, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useVolume1.setFont(font)
        self.pb_useVolume1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useVolume1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useVolume1.setFlat(True)
        self.pb_useVolume1.setObjectName(_fromUtf8("pb_useVolume1"))
        self.pb_sellNumber = QtGui.QPushButton(self.groupBox_2)
        self.pb_sellNumber.setGeometry(QtCore.QRect(410, 150, 50, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_sellNumber.setFont(font)
        self.pb_sellNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_sellNumber.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_sellNumber.setFlat(True)
        self.pb_sellNumber.setObjectName(_fromUtf8("pb_sellNumber"))
        self.pb_useVolume4 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useVolume4.setGeometry(QtCore.QRect(230, 120, 51, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useVolume4.setFont(font)
        self.pb_useVolume4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useVolume4.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useVolume4.setFlat(True)
        self.pb_useVolume4.setObjectName(_fromUtf8("pb_useVolume4"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(80, 150, 101, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.le_num = QtGui.QLineEdit(self.groupBox_2)
        self.le_num.setGeometry(QtCore.QRect(20, 280, 41, 20))
        self.le_num.setObjectName(_fromUtf8("le_num"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 220, 31, 16))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup = QtGui.QButtonGroup(SpeedApplyRedeem)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 260, 51, 16))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.buttonGroup.addButton(self.radioButton_4)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 240, 31, 16))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 200, 31, 16))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup.addButton(self.radioButton)
        self.pushButton_28 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_28.setGeometry(QtCore.QRect(360, 190, 75, 23))
        self.pushButton_28.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(1, 208, 25); }\n"
""))
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.pushButton_29 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_29.setGeometry(QtCore.QRect(90, 250, 75, 23))
        self.pushButton_29.setStyleSheet(_fromUtf8("QPushButton { background-color: rgb(255, 85, 0); }"))
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.pushButton_26 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_26.setGeometry(QtCore.QRect(180, 190, 75, 23))
        self.pushButton_26.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(1, 208, 25); }\n"
""))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.pushButton_30 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_30.setGeometry(QtCore.QRect(180, 250, 75, 23))
        self.pushButton_30.setStyleSheet(_fromUtf8("QPushButton { background-color: rgb(255, 85, 0); }"))
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.pushButton_31 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_31.setGeometry(QtCore.QRect(270, 250, 75, 23))
        self.pushButton_31.setStyleSheet(_fromUtf8("QPushButton { background-color: rgb(255, 85, 0); }"))
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(100, 220, 331, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Corbel"))
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("QLabel { border-radius: 3px; color: rgb(255, 0, 0); } "))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_32 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_32.setGeometry(QtCore.QRect(360, 250, 75, 23))
        self.pushButton_32.setStyleSheet(_fromUtf8("QPushButton { background-color: rgb(255, 85, 0); }"))
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.pushButton_27 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_27.setGeometry(QtCore.QRect(270, 190, 75, 23))
        self.pushButton_27.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(1, 208, 25); }\n"
""))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(100, 280, 331, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Corbel"))
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("QLabel { border-radius: 3px; color: rgb(255, 0, 0); } "))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_25 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_25.setGeometry(QtCore.QRect(90, 190, 75, 23))
        self.pushButton_25.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(1, 208, 25); }\n"
""))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        SpeedApplyRedeem.setWidget(self.dw_SpeedApplyRedeem)

        self.retranslateUi(SpeedApplyRedeem)
        QtCore.QMetaObject.connectSlotsByName(SpeedApplyRedeem)
        SpeedApplyRedeem.setTabOrder(self.le_stockCode, self.pb_buy)
        SpeedApplyRedeem.setTabOrder(self.pb_buy, self.pb_sell)
        SpeedApplyRedeem.setTabOrder(self.pb_sell, self.pushButton_25)
        SpeedApplyRedeem.setTabOrder(self.pushButton_25, self.pushButton_26)
        SpeedApplyRedeem.setTabOrder(self.pushButton_26, self.pushButton_27)
        SpeedApplyRedeem.setTabOrder(self.pushButton_27, self.pushButton_28)
        SpeedApplyRedeem.setTabOrder(self.pushButton_28, self.pushButton_29)
        SpeedApplyRedeem.setTabOrder(self.pushButton_29, self.pushButton_30)
        SpeedApplyRedeem.setTabOrder(self.pushButton_30, self.pushButton_31)
        SpeedApplyRedeem.setTabOrder(self.pushButton_31, self.pushButton_32)
        SpeedApplyRedeem.setTabOrder(self.pushButton_32, self.radioButton)
        SpeedApplyRedeem.setTabOrder(self.radioButton, self.radioButton_2)
        SpeedApplyRedeem.setTabOrder(self.radioButton_2, self.radioButton_3)
        SpeedApplyRedeem.setTabOrder(self.radioButton_3, self.radioButton_4)
        SpeedApplyRedeem.setTabOrder(self.radioButton_4, self.le_num)
        SpeedApplyRedeem.setTabOrder(self.le_num, self.pb_useCode4)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode4, self.pb_useCode5)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode5, self.pb_useCode6)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode6, self.pb_useCode7)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode7, self.pb_useCode8)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode8, self.pb_useVolume)
        SpeedApplyRedeem.setTabOrder(self.pb_useVolume, self.pb_useVolume1)
        SpeedApplyRedeem.setTabOrder(self.pb_useVolume1, self.pb_useVolume2)
        SpeedApplyRedeem.setTabOrder(self.pb_useVolume2, self.pb_useVolume3)
        SpeedApplyRedeem.setTabOrder(self.pb_useVolume3, self.pb_useVolume4)
        SpeedApplyRedeem.setTabOrder(self.pb_useVolume4, self.pb_useVolume5)
        SpeedApplyRedeem.setTabOrder(self.pb_useVolume5, self.pb_basket)
        SpeedApplyRedeem.setTabOrder(self.pb_basket, self.pb_useMoney)
        SpeedApplyRedeem.setTabOrder(self.pb_useMoney, self.pb_buzhunum)
        SpeedApplyRedeem.setTabOrder(self.pb_buzhunum, self.pb_sellNumber)
        SpeedApplyRedeem.setTabOrder(self.pb_sellNumber, self.pb_useCode)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode, self.pushButton_41)
        SpeedApplyRedeem.setTabOrder(self.pushButton_41, self.pb_useCode1)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode1, self.pb_useCode2)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode2, self.pb_useCode3)
        SpeedApplyRedeem.setTabOrder(self.pb_useCode3, self.pushButton_46)
        SpeedApplyRedeem.setTabOrder(self.pushButton_46, self.pb_info_money)
        SpeedApplyRedeem.setTabOrder(self.pb_info_money, self.pushButton_45)
        SpeedApplyRedeem.setTabOrder(self.pushButton_45, self.pushButton_49)
        SpeedApplyRedeem.setTabOrder(self.pushButton_49, self.pushButton_51)
        SpeedApplyRedeem.setTabOrder(self.pushButton_51, self.pb_b_money)
        SpeedApplyRedeem.setTabOrder(self.pb_b_money, self.pb_b_maxb)
        SpeedApplyRedeem.setTabOrder(self.pb_b_maxb, self.pb_s_money)
        SpeedApplyRedeem.setTabOrder(self.pb_s_money, self.pb_s1_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_s1_volume, self.pb_s3_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_s3_volume, self.pb_s2_price)
        SpeedApplyRedeem.setTabOrder(self.pb_s2_price, self.pb_s5_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_s5_volume, self.pb_s4_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_s4_volume, self.pb_s5_price)
        SpeedApplyRedeem.setTabOrder(self.pb_s5_price, self.pb_s1_price)
        SpeedApplyRedeem.setTabOrder(self.pb_s1_price, self.pb_s3_price)
        SpeedApplyRedeem.setTabOrder(self.pb_s3_price, self.pb_s4_price)
        SpeedApplyRedeem.setTabOrder(self.pb_s4_price, self.pb_s2_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_s2_volume, self.pb_b5_price)
        SpeedApplyRedeem.setTabOrder(self.pb_b5_price, self.pb_b5_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_b5_volume, self.pb_b3_price)
        SpeedApplyRedeem.setTabOrder(self.pb_b3_price, self.pb_b2_price)
        SpeedApplyRedeem.setTabOrder(self.pb_b2_price, self.pb_b1_price)
        SpeedApplyRedeem.setTabOrder(self.pb_b1_price, self.pb_b1_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_b1_volume, self.pb_b4_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_b4_volume, self.pb_b4_price)
        SpeedApplyRedeem.setTabOrder(self.pb_b4_price, self.pb_b2_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_b2_volume, self.pb_b3_volume)
        SpeedApplyRedeem.setTabOrder(self.pb_b3_volume, self.pushButton_52)
        SpeedApplyRedeem.setTabOrder(self.pushButton_52, self.pb_s_mins)

    def retranslateUi(self, SpeedApplyRedeem):
        SpeedApplyRedeem.setWindowTitle(_translate("SpeedApplyRedeem", "快速申赎", None))
        self.groupBox.setTitle(_translate("SpeedApplyRedeem", "行情数据显示", None))
        self.label.setText(_translate("SpeedApplyRedeem", "卖5", None))
        self.label_2.setText(_translate("SpeedApplyRedeem", "卖4", None))
        self.label_3.setText(_translate("SpeedApplyRedeem", "卖3", None))
        self.label_4.setText(_translate("SpeedApplyRedeem", "卖2", None))
        self.label_5.setText(_translate("SpeedApplyRedeem", "卖1", None))
        self.label_9.setText(_translate("SpeedApplyRedeem", "买1", None))
        self.label_12.setText(_translate("SpeedApplyRedeem", "买2", None))
        self.label_13.setText(_translate("SpeedApplyRedeem", "买3", None))
        self.label_14.setText(_translate("SpeedApplyRedeem", "买4", None))
        self.label_15.setText(_translate("SpeedApplyRedeem", "买5", None))
        self.pb_info_money.setText(_translate("SpeedApplyRedeem", "0.0万", None))
        self.pushButton_51.setText(_translate("SpeedApplyRedeem", "DIOPVS1", None))
        self.pushButton_49.setText(_translate("SpeedApplyRedeem", "2.200000", None))
        self.pushButton_52.setText(_translate("SpeedApplyRedeem", "1.900000", None))
        self.pushButton_46.setText(_translate("SpeedApplyRedeem", "DIOPVB1", None))
        self.pushButton_45.setText(_translate("SpeedApplyRedeem", "2.202", None))
        self.pushButton_41.setText(_translate("SpeedApplyRedeem", "IOPV", None))
        self.pb_b_money.setText(_translate("SpeedApplyRedeem", "0.0万", None))
        self.pb_s_money.setText(_translate("SpeedApplyRedeem", "0.0万", None))
        self.pb_s_mins.setText(_translate("SpeedApplyRedeem", "MinS 2.198", None))
        self.pb_b_maxb.setText(_translate("SpeedApplyRedeem", "MaxB 2.199", None))
        self.groupBox_2.setTitle(_translate("SpeedApplyRedeem", "交易操作", None))
        self.l_orderPrice_2.setText(_translate("SpeedApplyRedeem", "委托价格：", None))
        self.l_orderVolume_2.setText(_translate("SpeedApplyRedeem", "委托数量：", None))
        self.pb_sell.setText(_translate("SpeedApplyRedeem", "卖出(S)", None))
        self.pb_buy.setText(_translate("SpeedApplyRedeem", "买入(B)", None))
        self.l_stockCode.setText(_translate("SpeedApplyRedeem", "证券代码", None))
        self.pb_useCode1.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useCode5.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useCode4.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useCode8.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useCode.setText(_translate("SpeedApplyRedeem", "常用代码", None))
        self.pb_useCode3.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useCode7.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useCode6.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useCode2.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useMoney.setText(_translate("SpeedApplyRedeem", "可用资金", None))
        self.pb_useVolume.setText(_translate("SpeedApplyRedeem", "常用数量", None))
        self.l_basket.setText(_translate("SpeedApplyRedeem", "一篮子数", None))
        self.pb_buzhunum.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useVolume3.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.label_7.setText(_translate("SpeedApplyRedeem", "(万元)", None))
        self.l_sellNumber.setText(_translate("SpeedApplyRedeem", "可卖数", None))
        self.pb_useVolume2.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useVolume5.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.label_8.setText(_translate("SpeedApplyRedeem", "补足数", None))
        self.pb_basket.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useVolume1.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_sellNumber.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.pb_useVolume4.setText(_translate("SpeedApplyRedeem", "000001", None))
        self.label_6.setText(_translate("SpeedApplyRedeem", "123,123,12", None))
        self.radioButton_2.setText(_translate("SpeedApplyRedeem", "2", None))
        self.radioButton_4.setText(_translate("SpeedApplyRedeem", "更多", None))
        self.radioButton_3.setText(_translate("SpeedApplyRedeem", "3", None))
        self.radioButton.setText(_translate("SpeedApplyRedeem", "1", None))
        self.pushButton_28.setText(_translate("SpeedApplyRedeem", "卖篮子", None))
        self.pushButton_29.setText(_translate("SpeedApplyRedeem", "快申", None))
        self.pushButton_26.setText(_translate("SpeedApplyRedeem", "赎+卖", None))
        self.pushButton_30.setText(_translate("SpeedApplyRedeem", "买+申", None))
        self.pushButton_31.setText(_translate("SpeedApplyRedeem", "申赎", None))
        self.label_10.setText(_translate("SpeedApplyRedeem", "基金买入价格不能高于当前委托的最低价格2.199", None))
        self.pushButton_32.setText(_translate("SpeedApplyRedeem", "买篮子", None))
        self.pushButton_27.setText(_translate("SpeedApplyRedeem", "赎回", None))
        self.label_11.setText(_translate("SpeedApplyRedeem", "基金卖入价格不能低于当前委托的最高价格2.199", None))
        self.pushButton_25.setText(_translate("SpeedApplyRedeem", "快赎", None))

