# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockTrade.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StockTradeDock(object):
    def setupUi(self, StockTradeDock):
        StockTradeDock.setObjectName(_fromUtf8("StockTradeDock"))
        StockTradeDock.resize(577, 347)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StockTradeDock.sizePolicy().hasHeightForWidth())
        StockTradeDock.setSizePolicy(sizePolicy)
        StockTradeDock.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dw_SpeedApplyRedeem = QtGui.QWidget()
        self.dw_SpeedApplyRedeem.setEnabled(True)
        self.dw_SpeedApplyRedeem.setMinimumSize(QtCore.QSize(577, 317))
        self.dw_SpeedApplyRedeem.setObjectName(_fromUtf8("dw_SpeedApplyRedeem"))
        self.groupBox = QtGui.QGroupBox(self.dw_SpeedApplyRedeem)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 305))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pb_s1_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s1_volume.setGeometry(QtCore.QRect(120, 120, 61, 21))
        self.pb_s1_volume.setText(_fromUtf8(""))
        self.pb_s1_volume.setFlat(True)
        self.pb_s1_volume.setObjectName(_fromUtf8("pb_s1_volume"))
        self.pb_s3_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s3_volume.setGeometry(QtCore.QRect(120, 80, 61, 21))
        self.pb_s3_volume.setText(_fromUtf8(""))
        self.pb_s3_volume.setFlat(True)
        self.pb_s3_volume.setObjectName(_fromUtf8("pb_s3_volume"))
        self.pb_s2_price = QtGui.QPushButton(self.groupBox)
        self.pb_s2_price.setGeometry(QtCore.QRect(60, 100, 61, 21))
        self.pb_s2_price.setStyleSheet(_fromUtf8("\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.pb_s2_price.setText(_fromUtf8(""))
        self.pb_s2_price.setFlat(True)
        self.pb_s2_price.setObjectName(_fromUtf8("pb_s2_price"))
        self.pb_s5_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s5_volume.setGeometry(QtCore.QRect(120, 40, 61, 21))
        self.pb_s5_volume.setText(_fromUtf8(""))
        self.pb_s5_volume.setFlat(True)
        self.pb_s5_volume.setObjectName(_fromUtf8("pb_s5_volume"))
        self.pb_s4_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s4_volume.setGeometry(QtCore.QRect(120, 60, 61, 21))
        self.pb_s4_volume.setText(_fromUtf8(""))
        self.pb_s4_volume.setFlat(True)
        self.pb_s4_volume.setObjectName(_fromUtf8("pb_s4_volume"))
        self.pb_s5_price = QtGui.QPushButton(self.groupBox)
        self.pb_s5_price.setGeometry(QtCore.QRect(60, 40, 61, 21))
        self.pb_s5_price.setText(_fromUtf8(""))
        self.pb_s5_price.setFlat(True)
        self.pb_s5_price.setObjectName(_fromUtf8("pb_s5_price"))
        self.pb_s1_price = QtGui.QPushButton(self.groupBox)
        self.pb_s1_price.setGeometry(QtCore.QRect(60, 120, 61, 21))
        self.pb_s1_price.setStyleSheet(_fromUtf8(""))
        self.pb_s1_price.setText(_fromUtf8(""))
        self.pb_s1_price.setFlat(True)
        self.pb_s1_price.setObjectName(_fromUtf8("pb_s1_price"))
        self.pb_s3_price = QtGui.QPushButton(self.groupBox)
        self.pb_s3_price.setGeometry(QtCore.QRect(60, 80, 61, 21))
        self.pb_s3_price.setText(_fromUtf8(""))
        self.pb_s3_price.setFlat(True)
        self.pb_s3_price.setObjectName(_fromUtf8("pb_s3_price"))
        self.pb_harden_data = QtGui.QPushButton(self.groupBox)
        self.pb_harden_data.setGeometry(QtCore.QRect(60, 14, 60, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("ADMUI3Lg"))
        font.setBold(False)
        font.setWeight(50)
        self.pb_harden_data.setFont(font)
        self.pb_harden_data.setStyleSheet(_fromUtf8("QPushButton {color: rgb(255, 0, 0); } \n"
""))
        self.pb_harden_data.setText(_fromUtf8(""))
        self.pb_harden_data.setFlat(True)
        self.pb_harden_data.setObjectName(_fromUtf8("pb_harden_data"))
        self.pb_s4_price = QtGui.QPushButton(self.groupBox)
        self.pb_s4_price.setGeometry(QtCore.QRect(60, 60, 61, 21))
        self.pb_s4_price.setText(_fromUtf8(""))
        self.pb_s4_price.setFlat(True)
        self.pb_s4_price.setObjectName(_fromUtf8("pb_s4_price"))
        self.pb_harden = QtGui.QPushButton(self.groupBox)
        self.pb_harden.setGeometry(QtCore.QRect(10, 9, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setBold(False)
        font.setWeight(50)
        self.pb_harden.setFont(font)
        self.pb_harden.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); } \n"
"\n"
" "))
        self.pb_harden.setFlat(True)
        self.pb_harden.setObjectName(_fromUtf8("pb_harden"))
        self.pb_s2_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s2_volume.setGeometry(QtCore.QRect(120, 100, 61, 21))
        self.pb_s2_volume.setText(_fromUtf8(""))
        self.pb_s2_volume.setFlat(True)
        self.pb_s2_volume.setObjectName(_fromUtf8("pb_s2_volume"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(0, 140, 191, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.pb_b5_price = QtGui.QPushButton(self.groupBox)
        self.pb_b5_price.setGeometry(QtCore.QRect(60, 260, 61, 21))
        self.pb_b5_price.setText(_fromUtf8(""))
        self.pb_b5_price.setFlat(True)
        self.pb_b5_price.setObjectName(_fromUtf8("pb_b5_price"))
        self.pb_b5_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b5_volume.setGeometry(QtCore.QRect(120, 260, 61, 21))
        self.pb_b5_volume.setText(_fromUtf8(""))
        self.pb_b5_volume.setFlat(True)
        self.pb_b5_volume.setObjectName(_fromUtf8("pb_b5_volume"))
        self.pb_b3_price = QtGui.QPushButton(self.groupBox)
        self.pb_b3_price.setGeometry(QtCore.QRect(60, 220, 61, 21))
        self.pb_b3_price.setText(_fromUtf8(""))
        self.pb_b3_price.setFlat(True)
        self.pb_b3_price.setObjectName(_fromUtf8("pb_b3_price"))
        self.pb_b2_price = QtGui.QPushButton(self.groupBox)
        self.pb_b2_price.setGeometry(QtCore.QRect(60, 200, 61, 21))
        self.pb_b2_price.setText(_fromUtf8(""))
        self.pb_b2_price.setFlat(True)
        self.pb_b2_price.setObjectName(_fromUtf8("pb_b2_price"))
        self.pb_b1_price = QtGui.QPushButton(self.groupBox)
        self.pb_b1_price.setGeometry(QtCore.QRect(60, 180, 61, 21))
        self.pb_b1_price.setText(_fromUtf8(""))
        self.pb_b1_price.setFlat(True)
        self.pb_b1_price.setObjectName(_fromUtf8("pb_b1_price"))
        self.pb_b1_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b1_volume.setGeometry(QtCore.QRect(120, 180, 61, 21))
        self.pb_b1_volume.setText(_fromUtf8(""))
        self.pb_b1_volume.setFlat(True)
        self.pb_b1_volume.setObjectName(_fromUtf8("pb_b1_volume"))
        self.pb_b4_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b4_volume.setGeometry(QtCore.QRect(120, 240, 61, 21))
        self.pb_b4_volume.setText(_fromUtf8(""))
        self.pb_b4_volume.setFlat(True)
        self.pb_b4_volume.setObjectName(_fromUtf8("pb_b4_volume"))
        self.pb_limit = QtGui.QPushButton(self.groupBox)
        self.pb_limit.setGeometry(QtCore.QRect(10, 280, 51, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setBold(False)
        font.setWeight(50)
        self.pb_limit.setFont(font)
        self.pb_limit.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
""))
        self.pb_limit.setFlat(True)
        self.pb_limit.setObjectName(_fromUtf8("pb_limit"))
        self.pb_b4_price = QtGui.QPushButton(self.groupBox)
        self.pb_b4_price.setGeometry(QtCore.QRect(60, 240, 61, 21))
        self.pb_b4_price.setText(_fromUtf8(""))
        self.pb_b4_price.setFlat(True)
        self.pb_b4_price.setObjectName(_fromUtf8("pb_b4_price"))
        self.pb_b2_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b2_volume.setGeometry(QtCore.QRect(120, 200, 61, 21))
        self.pb_b2_volume.setText(_fromUtf8(""))
        self.pb_b2_volume.setFlat(True)
        self.pb_b2_volume.setObjectName(_fromUtf8("pb_b2_volume"))
        self.pb_b3_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b3_volume.setGeometry(QtCore.QRect(120, 220, 61, 21))
        self.pb_b3_volume.setText(_fromUtf8(""))
        self.pb_b3_volume.setFlat(True)
        self.pb_b3_volume.setObjectName(_fromUtf8("pb_b3_volume"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(0, 170, 191, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pb_cur_price = QtGui.QPushButton(self.groupBox)
        self.pb_cur_price.setGeometry(QtCore.QRect(60, 150, 71, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_cur_price.sizePolicy().hasHeightForWidth())
        self.pb_cur_price.setSizePolicy(sizePolicy)
        self.pb_cur_price.setText(_fromUtf8(""))
        self.pb_cur_price.setFlat(True)
        self.pb_cur_price.setObjectName(_fromUtf8("pb_cur_price"))
        self.pb_limit_data = QtGui.QPushButton(self.groupBox)
        self.pb_limit_data.setGeometry(QtCore.QRect(60, 280, 61, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("ADMUI3Lg"))
        self.pb_limit_data.setFont(font)
        self.pb_limit_data.setStyleSheet(_fromUtf8("QPushButton {color: rgb(1, 208, 25); } "))
        self.pb_limit_data.setText(_fromUtf8(""))
        self.pb_limit_data.setFlat(True)
        self.pb_limit_data.setObjectName(_fromUtf8("pb_limit_data"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 51, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 51, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 51, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 51, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 51, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 51, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 51, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_2 = QtGui.QGroupBox(self.dw_SpeedApplyRedeem)
        self.groupBox_2.setGeometry(QtCore.QRect(207, 10, 360, 305))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.le_stockCode = QtGui.QLineEdit(self.groupBox_2)
        self.le_stockCode.setGeometry(QtCore.QRect(80, 30, 81, 20))
        self.le_stockCode.setMaxLength(6)
        self.le_stockCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_stockCode.setObjectName(_fromUtf8("le_stockCode"))
        self.l_orderPrice = QtGui.QLabel(self.groupBox_2)
        self.l_orderPrice.setGeometry(QtCore.QRect(180, 30, 54, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_orderPrice.sizePolicy().hasHeightForWidth())
        self.l_orderPrice.setSizePolicy(sizePolicy)
        self.l_orderPrice.setObjectName(_fromUtf8("l_orderPrice"))
        self.l_stockCode = QtGui.QLabel(self.groupBox_2)
        self.l_stockCode.setGeometry(QtCore.QRect(20, 30, 54, 20))
        self.l_stockCode.setObjectName(_fromUtf8("l_stockCode"))
        self.l_stockName_data = QtGui.QLabel(self.groupBox_2)
        self.l_stockName_data.setGeometry(QtCore.QRect(80, 60, 81, 20))
        self.l_stockName_data.setText(_fromUtf8(""))
        self.l_stockName_data.setObjectName(_fromUtf8("l_stockName_data"))
        self.l_stockName = QtGui.QLabel(self.groupBox_2)
        self.l_stockName.setGeometry(QtCore.QRect(20, 60, 54, 20))
        self.l_stockName.setObjectName(_fromUtf8("l_stockName"))
        self.l_orderVolume = QtGui.QLabel(self.groupBox_2)
        self.l_orderVolume.setGeometry(QtCore.QRect(180, 60, 54, 20))
        self.l_orderVolume.setObjectName(_fromUtf8("l_orderVolume"))
        self.pb_sell = QtGui.QPushButton(self.groupBox_2)
        self.pb_sell.setGeometry(QtCore.QRect(220, 97, 75, 23))
        self.pb_sell.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }\n"
""))
        self.pb_sell.setObjectName(_fromUtf8("pb_sell"))
        self.pb_buy = QtGui.QPushButton(self.groupBox_2)
        self.pb_buy.setGeometry(QtCore.QRect(90, 97, 75, 23))
        self.pb_buy.setStyleSheet(_fromUtf8("QPushButton { background-color: #FF0000}"))
        self.pb_buy.setObjectName(_fromUtf8("pb_buy"))
        self.pb_useCode5 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode5.setGeometry(QtCore.QRect(290, 160, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode5.setFont(font)
        self.pb_useCode5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode5.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode5.setFlat(True)
        self.pb_useCode5.setObjectName(_fromUtf8("pb_useCode5"))
        self.pb_useCode4 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode4.setGeometry(QtCore.QRect(240, 160, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode4.setFont(font)
        self.pb_useCode4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode4.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode4.setFlat(True)
        self.pb_useCode4.setObjectName(_fromUtf8("pb_useCode4"))
        self.pb_useCode = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode.setGeometry(QtCore.QRect(20, 160, 61, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setUnderline(True)
        self.pb_useCode.setFont(font)
        self.pb_useCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
" "))
        self.pb_useCode.setFlat(True)
        self.pb_useCode.setObjectName(_fromUtf8("pb_useCode"))
        self.pb_useCode1 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode1.setGeometry(QtCore.QRect(90, 160, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode1.setFont(font)
        self.pb_useCode1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode1.setFlat(True)
        self.pb_useCode1.setObjectName(_fromUtf8("pb_useCode1"))
        self.pb_useCode8 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode8.setGeometry(QtCore.QRect(190, 180, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode8.setFont(font)
        self.pb_useCode8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode8.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode8.setFlat(True)
        self.pb_useCode8.setObjectName(_fromUtf8("pb_useCode8"))
        self.pb_useCode3 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode3.setGeometry(QtCore.QRect(190, 160, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode3.setFont(font)
        self.pb_useCode3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode3.setFlat(True)
        self.pb_useCode3.setObjectName(_fromUtf8("pb_useCode3"))
        self.pb_useCode2 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode2.setGeometry(QtCore.QRect(140, 160, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode2.setFont(font)
        self.pb_useCode2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode2.setFlat(True)
        self.pb_useCode2.setObjectName(_fromUtf8("pb_useCode2"))
        self.pb_useCode10 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode10.setGeometry(QtCore.QRect(290, 180, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode10.setFont(font)
        self.pb_useCode10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode10.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode10.setFlat(True)
        self.pb_useCode10.setObjectName(_fromUtf8("pb_useCode10"))
        self.pb_useCode9 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode9.setGeometry(QtCore.QRect(240, 180, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode9.setFont(font)
        self.pb_useCode9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode9.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode9.setFlat(True)
        self.pb_useCode9.setObjectName(_fromUtf8("pb_useCode9"))
        self.pb_useCode7 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode7.setGeometry(QtCore.QRect(140, 180, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode7.setFont(font)
        self.pb_useCode7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode7.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode7.setFlat(True)
        self.pb_useCode7.setObjectName(_fromUtf8("pb_useCode7"))
        self.pb_useCode6 = QtGui.QPushButton(self.groupBox_2)
        self.pb_useCode6.setGeometry(QtCore.QRect(90, 180, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode6.setFont(font)
        self.pb_useCode6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode6.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode6.setFlat(True)
        self.pb_useCode6.setObjectName(_fromUtf8("pb_useCode6"))
        self.l_orderVolume_8 = QtGui.QLabel(self.groupBox_2)
        self.l_orderVolume_8.setGeometry(QtCore.QRect(220, 270, 31, 21))
        self.l_orderVolume_8.setObjectName(_fromUtf8("l_orderVolume_8"))
        self.l_money = QtGui.QLabel(self.groupBox_2)
        self.l_money.setGeometry(QtCore.QRect(90, 270, 121, 20))
        self.l_money.setText(_fromUtf8(""))
        self.l_money.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_money.setObjectName(_fromUtf8("l_money"))
        self.pb_useMoney = QtGui.QPushButton(self.groupBox_2)
        self.pb_useMoney.setGeometry(QtCore.QRect(20, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setUnderline(True)
        self.pb_useMoney.setFont(font)
        self.pb_useMoney.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useMoney.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useMoney.setFlat(True)
        self.pb_useMoney.setObjectName(_fromUtf8("pb_useMoney"))
        self.l_canBuyVolume = QtGui.QLabel(self.groupBox_2)
        self.l_canBuyVolume.setGeometry(QtCore.QRect(20, 210, 54, 20))
        self.l_canBuyVolume.setObjectName(_fromUtf8("l_canBuyVolume"))
        self.l_canSellVolume_data = QtGui.QLabel(self.groupBox_2)
        self.l_canSellVolume_data.setGeometry(QtCore.QRect(90, 239, 91, 21))
        self.l_canSellVolume_data.setText(_fromUtf8(""))
        self.l_canSellVolume_data.setObjectName(_fromUtf8("l_canSellVolume_data"))
        self.l_canSellVolume = QtGui.QLabel(self.groupBox_2)
        self.l_canSellVolume.setGeometry(QtCore.QRect(20, 239, 54, 21))
        self.l_canSellVolume.setObjectName(_fromUtf8("l_canSellVolume"))
        self.l_canBuyVolume_data = QtGui.QLabel(self.groupBox_2)
        self.l_canBuyVolume_data.setGeometry(QtCore.QRect(90, 210, 91, 20))
        self.l_canBuyVolume_data.setText(_fromUtf8(""))
        self.l_canBuyVolume_data.setObjectName(_fromUtf8("l_canBuyVolume_data"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(50, 130, 251, 21))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        StockTradeDock.setWidget(self.dw_SpeedApplyRedeem)

        self.retranslateUi(StockTradeDock)
        QtCore.QMetaObject.connectSlotsByName(StockTradeDock)
        StockTradeDock.setTabOrder(self.le_stockCode, self.pb_buy)
        StockTradeDock.setTabOrder(self.pb_buy, self.pb_sell)
        StockTradeDock.setTabOrder(self.pb_sell, self.pb_useCode3)
        StockTradeDock.setTabOrder(self.pb_useCode3, self.pb_useCode4)
        StockTradeDock.setTabOrder(self.pb_useCode4, self.pb_useCode5)
        StockTradeDock.setTabOrder(self.pb_useCode5, self.pb_useCode6)
        StockTradeDock.setTabOrder(self.pb_useCode6, self.pb_useCode7)
        StockTradeDock.setTabOrder(self.pb_useCode7, self.pb_useCode8)
        StockTradeDock.setTabOrder(self.pb_useCode8, self.pb_useCode1)
        StockTradeDock.setTabOrder(self.pb_useCode1, self.pb_useCode)
        StockTradeDock.setTabOrder(self.pb_useCode, self.pb_useCode9)
        StockTradeDock.setTabOrder(self.pb_useCode9, self.pb_useCode10)
        StockTradeDock.setTabOrder(self.pb_useCode10, self.pb_useMoney)
        StockTradeDock.setTabOrder(self.pb_useMoney, self.pb_cur_price)
        StockTradeDock.setTabOrder(self.pb_cur_price, self.pb_b3_price)
        StockTradeDock.setTabOrder(self.pb_b3_price, self.pb_b5_price)
        StockTradeDock.setTabOrder(self.pb_b5_price, self.pb_b2_price)
        StockTradeDock.setTabOrder(self.pb_b2_price, self.pb_b1_price)
        StockTradeDock.setTabOrder(self.pb_b1_price, self.pb_b4_price)
        StockTradeDock.setTabOrder(self.pb_b4_price, self.pb_b1_volume)
        StockTradeDock.setTabOrder(self.pb_b1_volume, self.pb_b4_volume)
        StockTradeDock.setTabOrder(self.pb_b4_volume, self.pb_b5_volume)
        StockTradeDock.setTabOrder(self.pb_b5_volume, self.pb_b2_volume)
        StockTradeDock.setTabOrder(self.pb_b2_volume, self.pb_b3_volume)
        StockTradeDock.setTabOrder(self.pb_b3_volume, self.pb_limit)
        StockTradeDock.setTabOrder(self.pb_limit, self.pb_s3_price)
        StockTradeDock.setTabOrder(self.pb_s3_price, self.pb_s1_price)
        StockTradeDock.setTabOrder(self.pb_s1_price, self.pb_s4_price)
        StockTradeDock.setTabOrder(self.pb_s4_price, self.pb_s5_price)
        StockTradeDock.setTabOrder(self.pb_s5_price, self.pb_s2_price)
        StockTradeDock.setTabOrder(self.pb_s2_price, self.pb_s5_volume)
        StockTradeDock.setTabOrder(self.pb_s5_volume, self.pb_s2_volume)
        StockTradeDock.setTabOrder(self.pb_s2_volume, self.pb_s1_volume)
        StockTradeDock.setTabOrder(self.pb_s1_volume, self.pb_s4_volume)
        StockTradeDock.setTabOrder(self.pb_s4_volume, self.pb_s3_volume)
        StockTradeDock.setTabOrder(self.pb_s3_volume, self.pb_harden)
        StockTradeDock.setTabOrder(self.pb_harden, self.pb_harden_data)
        StockTradeDock.setTabOrder(self.pb_harden_data, self.pb_useCode2)

    def retranslateUi(self, StockTradeDock):
        StockTradeDock.setWindowTitle(_translate("StockTradeDock", "股票买卖", None))
        self.groupBox.setTitle(_translate("StockTradeDock", "行情数据显示", None))
        self.pb_harden.setText(_translate("StockTradeDock", "涨停价", None))
        self.pb_limit.setText(_translate("StockTradeDock", "跌停价", None))
        self.label.setText(_translate("StockTradeDock", "卖5", None))
        self.label_2.setText(_translate("StockTradeDock", "卖4", None))
        self.label_3.setText(_translate("StockTradeDock", "卖3", None))
        self.label_4.setText(_translate("StockTradeDock", "卖2", None))
        self.label_5.setText(_translate("StockTradeDock", "卖1", None))
        self.label_6.setText(_translate("StockTradeDock", "买1", None))
        self.label_7.setText(_translate("StockTradeDock", "买2", None))
        self.label_8.setText(_translate("StockTradeDock", "买3", None))
        self.label_9.setText(_translate("StockTradeDock", "买4", None))
        self.label_10.setText(_translate("StockTradeDock", "买5", None))
        self.label_11.setText(_translate("StockTradeDock", "最新价", None))
        self.groupBox_2.setTitle(_translate("StockTradeDock", "交易操作", None))
        self.l_orderPrice.setText(_translate("StockTradeDock", "委托价格：", None))
        self.l_stockCode.setText(_translate("StockTradeDock", "股票代码：", None))
        self.l_stockName.setText(_translate("StockTradeDock", "股票名称：", None))
        self.l_orderVolume.setText(_translate("StockTradeDock", "委托数量：", None))
        self.pb_sell.setText(_translate("StockTradeDock", "卖出(S)", None))
        self.pb_buy.setText(_translate("StockTradeDock", "买入(B)", None))
        self.pb_useCode5.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode4.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode.setText(_translate("StockTradeDock", "常用代码：", None))
        self.pb_useCode1.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode8.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode3.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode2.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode10.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode9.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode7.setText(_translate("StockTradeDock", "000001", None))
        self.pb_useCode6.setText(_translate("StockTradeDock", "000001", None))
        self.l_orderVolume_8.setText(_translate("StockTradeDock", "(元)", None))
        self.pb_useMoney.setText(_translate("StockTradeDock", "可用资金：", None))
        self.l_canBuyVolume.setText(_translate("StockTradeDock", "可买数量：", None))
        self.l_canSellVolume.setText(_translate("StockTradeDock", "可卖数量：", None))

