# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StrFundTrade.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWdget(object):
    def setupUi(self, DockWdget):
        DockWdget.setObjectName(_fromUtf8("DockWdget"))
        DockWdget.resize(795, 363)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 321))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pb_s1_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s1_volume.setGeometry(QtCore.QRect(120, 120, 61, 21))
        self.pb_s1_volume.setText(_fromUtf8(""))
        self.pb_s1_volume.setFlat(True)
        self.pb_s1_volume.setObjectName(_fromUtf8("pb_s1_volume"))
        self.pb_s3_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s3_volume.setGeometry(QtCore.QRect(120, 80, 61, 21))
        self.pb_s3_volume.setText(_fromUtf8(""))
        self.pb_s3_volume.setFlat(True)
        self.pb_s3_volume.setObjectName(_fromUtf8("pb_s3_volume"))
        self.pb_s2_price = QtGui.QPushButton(self.groupBox)
        self.pb_s2_price.setGeometry(QtCore.QRect(60, 100, 61, 21))
        self.pb_s2_price.setStyleSheet(_fromUtf8("\n"
"QPushButton:hover { background-color: rgb(89, 89, 89); }\n"
""))
        self.pb_s2_price.setText(_fromUtf8(""))
        self.pb_s2_price.setFlat(True)
        self.pb_s2_price.setObjectName(_fromUtf8("pb_s2_price"))
        self.pb_s5_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s5_volume.setGeometry(QtCore.QRect(120, 40, 61, 21))
        self.pb_s5_volume.setText(_fromUtf8(""))
        self.pb_s5_volume.setFlat(True)
        self.pb_s5_volume.setObjectName(_fromUtf8("pb_s5_volume"))
        self.pb_s4_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s4_volume.setGeometry(QtCore.QRect(120, 60, 61, 21))
        self.pb_s4_volume.setText(_fromUtf8(""))
        self.pb_s4_volume.setFlat(True)
        self.pb_s4_volume.setObjectName(_fromUtf8("pb_s4_volume"))
        self.pb_s5_price = QtGui.QPushButton(self.groupBox)
        self.pb_s5_price.setGeometry(QtCore.QRect(60, 40, 61, 21))
        self.pb_s5_price.setText(_fromUtf8(""))
        self.pb_s5_price.setFlat(True)
        self.pb_s5_price.setObjectName(_fromUtf8("pb_s5_price"))
        self.pb_s1_price = QtGui.QPushButton(self.groupBox)
        self.pb_s1_price.setGeometry(QtCore.QRect(60, 120, 61, 21))
        self.pb_s1_price.setStyleSheet(_fromUtf8(""))
        self.pb_s1_price.setText(_fromUtf8(""))
        self.pb_s1_price.setFlat(True)
        self.pb_s1_price.setObjectName(_fromUtf8("pb_s1_price"))
        self.pb_s3_price = QtGui.QPushButton(self.groupBox)
        self.pb_s3_price.setGeometry(QtCore.QRect(60, 80, 61, 21))
        self.pb_s3_price.setText(_fromUtf8(""))
        self.pb_s3_price.setFlat(True)
        self.pb_s3_price.setObjectName(_fromUtf8("pb_s3_price"))
        self.pb_harden_data = QtGui.QPushButton(self.groupBox)
        self.pb_harden_data.setGeometry(QtCore.QRect(60, 14, 60, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("ADMUI3Lg"))
        font.setBold(False)
        font.setWeight(50)
        self.pb_harden_data.setFont(font)
        self.pb_harden_data.setStyleSheet(_fromUtf8("QPushButton {color: rgb(255, 0, 0); } \n"
""))
        self.pb_harden_data.setText(_fromUtf8(""))
        self.pb_harden_data.setFlat(True)
        self.pb_harden_data.setObjectName(_fromUtf8("pb_harden_data"))
        self.pb_s4_price = QtGui.QPushButton(self.groupBox)
        self.pb_s4_price.setGeometry(QtCore.QRect(60, 60, 61, 21))
        self.pb_s4_price.setText(_fromUtf8(""))
        self.pb_s4_price.setFlat(True)
        self.pb_s4_price.setObjectName(_fromUtf8("pb_s4_price"))
        self.pb_harden = QtGui.QPushButton(self.groupBox)
        self.pb_harden.setGeometry(QtCore.QRect(10, 9, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setBold(False)
        font.setWeight(50)
        self.pb_harden.setFont(font)
        self.pb_harden.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(255, 0, 0); } \n"
"\n"
" "))
        self.pb_harden.setFlat(True)
        self.pb_harden.setObjectName(_fromUtf8("pb_harden"))
        self.pb_s2_volume = QtGui.QPushButton(self.groupBox)
        self.pb_s2_volume.setGeometry(QtCore.QRect(120, 100, 61, 21))
        self.pb_s2_volume.setText(_fromUtf8(""))
        self.pb_s2_volume.setFlat(True)
        self.pb_s2_volume.setObjectName(_fromUtf8("pb_s2_volume"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(0, 140, 191, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.pb_b5_price = QtGui.QPushButton(self.groupBox)
        self.pb_b5_price.setGeometry(QtCore.QRect(60, 270, 61, 21))
        self.pb_b5_price.setText(_fromUtf8(""))
        self.pb_b5_price.setFlat(True)
        self.pb_b5_price.setObjectName(_fromUtf8("pb_b5_price"))
        self.pb_b5_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b5_volume.setGeometry(QtCore.QRect(120, 270, 61, 21))
        self.pb_b5_volume.setText(_fromUtf8(""))
        self.pb_b5_volume.setFlat(True)
        self.pb_b5_volume.setObjectName(_fromUtf8("pb_b5_volume"))
        self.pb_b3_price = QtGui.QPushButton(self.groupBox)
        self.pb_b3_price.setGeometry(QtCore.QRect(60, 230, 61, 21))
        self.pb_b3_price.setText(_fromUtf8(""))
        self.pb_b3_price.setFlat(True)
        self.pb_b3_price.setObjectName(_fromUtf8("pb_b3_price"))
        self.pb_b2_price = QtGui.QPushButton(self.groupBox)
        self.pb_b2_price.setGeometry(QtCore.QRect(60, 210, 61, 21))
        self.pb_b2_price.setText(_fromUtf8(""))
        self.pb_b2_price.setFlat(True)
        self.pb_b2_price.setObjectName(_fromUtf8("pb_b2_price"))
        self.pb_b1_price = QtGui.QPushButton(self.groupBox)
        self.pb_b1_price.setGeometry(QtCore.QRect(60, 190, 61, 21))
        self.pb_b1_price.setText(_fromUtf8(""))
        self.pb_b1_price.setFlat(True)
        self.pb_b1_price.setObjectName(_fromUtf8("pb_b1_price"))
        self.pb_b1_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b1_volume.setGeometry(QtCore.QRect(120, 190, 61, 21))
        self.pb_b1_volume.setText(_fromUtf8(""))
        self.pb_b1_volume.setFlat(True)
        self.pb_b1_volume.setObjectName(_fromUtf8("pb_b1_volume"))
        self.pb_b4_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b4_volume.setGeometry(QtCore.QRect(120, 250, 61, 21))
        self.pb_b4_volume.setText(_fromUtf8(""))
        self.pb_b4_volume.setFlat(True)
        self.pb_b4_volume.setObjectName(_fromUtf8("pb_b4_volume"))
        self.pb_limit = QtGui.QPushButton(self.groupBox)
        self.pb_limit.setGeometry(QtCore.QRect(10, 290, 51, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setBold(False)
        font.setWeight(50)
        self.pb_limit.setFont(font)
        self.pb_limit.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 208, 25); } \n"
""))
        self.pb_limit.setFlat(True)
        self.pb_limit.setObjectName(_fromUtf8("pb_limit"))
        self.pb_b4_price = QtGui.QPushButton(self.groupBox)
        self.pb_b4_price.setGeometry(QtCore.QRect(60, 250, 61, 21))
        self.pb_b4_price.setText(_fromUtf8(""))
        self.pb_b4_price.setFlat(True)
        self.pb_b4_price.setObjectName(_fromUtf8("pb_b4_price"))
        self.pb_b2_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b2_volume.setGeometry(QtCore.QRect(120, 210, 61, 21))
        self.pb_b2_volume.setText(_fromUtf8(""))
        self.pb_b2_volume.setFlat(True)
        self.pb_b2_volume.setObjectName(_fromUtf8("pb_b2_volume"))
        self.pb_b3_volume = QtGui.QPushButton(self.groupBox)
        self.pb_b3_volume.setGeometry(QtCore.QRect(120, 230, 61, 21))
        self.pb_b3_volume.setText(_fromUtf8(""))
        self.pb_b3_volume.setFlat(True)
        self.pb_b3_volume.setObjectName(_fromUtf8("pb_b3_volume"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(0, 180, 191, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pb_cur_price = QtGui.QPushButton(self.groupBox)
        self.pb_cur_price.setGeometry(QtCore.QRect(60, 150, 71, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_cur_price.sizePolicy().hasHeightForWidth())
        self.pb_cur_price.setSizePolicy(sizePolicy)
        self.pb_cur_price.setText(_fromUtf8(""))
        self.pb_cur_price.setFlat(True)
        self.pb_cur_price.setObjectName(_fromUtf8("pb_cur_price"))
        self.pb_limit_data = QtGui.QPushButton(self.groupBox)
        self.pb_limit_data.setGeometry(QtCore.QRect(60, 290, 61, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("ADMUI3Lg"))
        self.pb_limit_data.setFont(font)
        self.pb_limit_data.setStyleSheet(_fromUtf8("QPushButton {color: rgb(1, 208, 25); } "))
        self.pb_limit_data.setText(_fromUtf8(""))
        self.pb_limit_data.setFlat(True)
        self.pb_limit_data.setObjectName(_fromUtf8("pb_limit_data"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 51, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 51, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 51, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 51, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 51, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 51, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 270, 51, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 51, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(207, 10, 381, 101))
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox{background-color:rgb(229, 229, 229)}"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.le_stockCode = QtGui.QLineEdit(self.groupBox_2)
        self.le_stockCode.setGeometry(QtCore.QRect(80, 20, 81, 20))
        self.le_stockCode.setMaxLength(6)
        self.le_stockCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_stockCode.setObjectName(_fromUtf8("le_stockCode"))
        self.l_orderPrice = QtGui.QLabel(self.groupBox_2)
        self.l_orderPrice.setGeometry(QtCore.QRect(180, 20, 54, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_orderPrice.sizePolicy().hasHeightForWidth())
        self.l_orderPrice.setSizePolicy(sizePolicy)
        self.l_orderPrice.setObjectName(_fromUtf8("l_orderPrice"))
        self.l_stockCode = QtGui.QLabel(self.groupBox_2)
        self.l_stockCode.setGeometry(QtCore.QRect(13, 20, 61, 20))
        self.l_stockCode.setObjectName(_fromUtf8("l_stockCode"))
        self.l_orderVolume = QtGui.QLabel(self.groupBox_2)
        self.l_orderVolume.setGeometry(QtCore.QRect(13, 50, 61, 20))
        self.l_orderVolume.setObjectName(_fromUtf8("l_orderVolume"))
        self.pb_sell = QtGui.QPushButton(self.groupBox_2)
        self.pb_sell.setGeometry(QtCore.QRect(270, 53, 75, 23))
        self.pb_sell.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }\n"
""))
        self.pb_sell.setObjectName(_fromUtf8("pb_sell"))
        self.pb_buy = QtGui.QPushButton(self.groupBox_2)
        self.pb_buy.setGeometry(QtCore.QRect(180, 54, 75, 23))
        self.pb_buy.setStyleSheet(_fromUtf8("QPushButton { background-color: #FF0000}"))
        self.pb_buy.setObjectName(_fromUtf8("pb_buy"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pb_useCode4 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode4.setGeometry(QtCore.QRect(440, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode4.setFont(font)
        self.pb_useCode4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode4.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode4.setFlat(True)
        self.pb_useCode4.setObjectName(_fromUtf8("pb_useCode4"))
        self.pb_useCode8 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode8.setGeometry(QtCore.QRect(640, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode8.setFont(font)
        self.pb_useCode8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode8.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode8.setFlat(True)
        self.pb_useCode8.setObjectName(_fromUtf8("pb_useCode8"))
        self.pb_useCode3 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode3.setGeometry(QtCore.QRect(390, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode3.setFont(font)
        self.pb_useCode3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode3.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode3.setFlat(True)
        self.pb_useCode3.setObjectName(_fromUtf8("pb_useCode3"))
        self.pb_useCode2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode2.setGeometry(QtCore.QRect(340, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode2.setFont(font)
        self.pb_useCode2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode2.setFlat(True)
        self.pb_useCode2.setObjectName(_fromUtf8("pb_useCode2"))
        self.pb_useCode = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode.setGeometry(QtCore.QRect(220, 290, 61, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setUnderline(True)
        self.pb_useCode.setFont(font)
        self.pb_useCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
" "))
        self.pb_useCode.setFlat(True)
        self.pb_useCode.setObjectName(_fromUtf8("pb_useCode"))
        self.pb_useCode1 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode1.setGeometry(QtCore.QRect(290, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode1.setFont(font)
        self.pb_useCode1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode1.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode1.setFlat(True)
        self.pb_useCode1.setObjectName(_fromUtf8("pb_useCode1"))
        self.pb_useCode7 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode7.setGeometry(QtCore.QRect(590, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode7.setFont(font)
        self.pb_useCode7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode7.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode7.setFlat(True)
        self.pb_useCode7.setObjectName(_fromUtf8("pb_useCode7"))
        self.pb_useCode6 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode6.setGeometry(QtCore.QRect(540, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode6.setFont(font)
        self.pb_useCode6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode6.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode6.setFlat(True)
        self.pb_useCode6.setObjectName(_fromUtf8("pb_useCode6"))
        self.pb_useCode5 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode5.setGeometry(QtCore.QRect(490, 291, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode5.setFont(font)
        self.pb_useCode5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode5.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode5.setFlat(True)
        self.pb_useCode5.setObjectName(_fromUtf8("pb_useCode5"))
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(600, 10, 191, 281))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 41, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 50, 75, 23))
        self.pushButton_2.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_8.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(255, 106, 0) }"))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.pushButton_9.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(255, 106, 0) }"))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton_10.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(255, 106, 0) }"))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.pushButton_11.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(255, 106, 0) }"))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.pushButton_12.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }"))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.pushButton_13.setStyleSheet(_fromUtf8("QPushButton { background-color:rgb(255, 106, 0) }"))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_14.setGeometry(QtCore.QRect(100, 90, 75, 23))
        self.pushButton_14.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }"))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_15.setGeometry(QtCore.QRect(100, 130, 75, 23))
        self.pushButton_15.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }"))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_16.setGeometry(QtCore.QRect(100, 170, 75, 23))
        self.pushButton_16.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }"))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_17.setGeometry(QtCore.QRect(100, 210, 75, 23))
        self.pushButton_17.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }"))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_18.setGeometry(QtCore.QRect(100, 250, 75, 23))
        self.pushButton_18.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }"))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pb_useCode4_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode4_2.setGeometry(QtCore.QRect(440, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode4_2.setFont(font)
        self.pb_useCode4_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode4_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode4_2.setFlat(True)
        self.pb_useCode4_2.setObjectName(_fromUtf8("pb_useCode4_2"))
        self.pb_useCode8_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode8_2.setGeometry(QtCore.QRect(640, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode8_2.setFont(font)
        self.pb_useCode8_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode8_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode8_2.setFlat(True)
        self.pb_useCode8_2.setObjectName(_fromUtf8("pb_useCode8_2"))
        self.pb_useCode3_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode3_2.setGeometry(QtCore.QRect(390, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode3_2.setFont(font)
        self.pb_useCode3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode3_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode3_2.setFlat(True)
        self.pb_useCode3_2.setObjectName(_fromUtf8("pb_useCode3_2"))
        self.pb_useCode2_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode2_2.setGeometry(QtCore.QRect(340, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode2_2.setFont(font)
        self.pb_useCode2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode2_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode2_2.setFlat(True)
        self.pb_useCode2_2.setObjectName(_fromUtf8("pb_useCode2_2"))
        self.pb_useCode_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode_2.setGeometry(QtCore.QRect(220, 312, 61, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setUnderline(True)
        self.pb_useCode_2.setFont(font)
        self.pb_useCode_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); }\n"
" "))
        self.pb_useCode_2.setFlat(True)
        self.pb_useCode_2.setObjectName(_fromUtf8("pb_useCode_2"))
        self.pb_useCode1_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode1_2.setGeometry(QtCore.QRect(290, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode1_2.setFont(font)
        self.pb_useCode1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode1_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode1_2.setFlat(True)
        self.pb_useCode1_2.setObjectName(_fromUtf8("pb_useCode1_2"))
        self.pb_useCode7_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode7_2.setGeometry(QtCore.QRect(590, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode7_2.setFont(font)
        self.pb_useCode7_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode7_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode7_2.setFlat(True)
        self.pb_useCode7_2.setObjectName(_fromUtf8("pb_useCode7_2"))
        self.pb_useCode6_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode6_2.setGeometry(QtCore.QRect(540, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode6_2.setFont(font)
        self.pb_useCode6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode6_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode6_2.setFlat(True)
        self.pb_useCode6_2.setObjectName(_fromUtf8("pb_useCode6_2"))
        self.pb_useCode5_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pb_useCode5_2.setGeometry(QtCore.QRect(490, 313, 41, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dotum"))
        font.setPointSize(10)
        font.setUnderline(True)
        self.pb_useCode5_2.setFont(font)
        self.pb_useCode5_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_useCode5_2.setStyleSheet(_fromUtf8("QPushButton { border-radius: 3px; color: rgb(1, 170, 255); } \n"
"\n"
""))
        self.pb_useCode5_2.setFlat(True)
        self.pb_useCode5_2.setObjectName(_fromUtf8("pb_useCode5_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_4.setGeometry(QtCore.QRect(207, 110, 381, 91))
        self.groupBox_4.setStyleSheet(_fromUtf8("QGroupBox{background-color:rgb(229, 229, 229)}"))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pb_buy_2 = QtGui.QPushButton(self.groupBox_4)
        self.pb_buy_2.setGeometry(QtCore.QRect(180, 40, 75, 23))
        self.pb_buy_2.setStyleSheet(_fromUtf8("QPushButton { background-color: #FF0000}"))
        self.pb_buy_2.setObjectName(_fromUtf8("pb_buy_2"))
        self.pb_sell_2 = QtGui.QPushButton(self.groupBox_4)
        self.pb_sell_2.setGeometry(QtCore.QRect(270, 40, 75, 23))
        self.pb_sell_2.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }\n"
""))
        self.pb_sell_2.setObjectName(_fromUtf8("pb_sell_2"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.l_stockCode_2 = QtGui.QLabel(self.groupBox_4)
        self.l_stockCode_2.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.l_stockCode_2.setObjectName(_fromUtf8("l_stockCode_2"))
        self.le_stockCode_2 = QtGui.QLineEdit(self.groupBox_4)
        self.le_stockCode_2.setGeometry(QtCore.QRect(80, 10, 81, 20))
        self.le_stockCode_2.setText(_fromUtf8(""))
        self.le_stockCode_2.setMaxLength(6)
        self.le_stockCode_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_stockCode_2.setObjectName(_fromUtf8("le_stockCode_2"))
        self.l_orderPrice_2 = QtGui.QLabel(self.groupBox_4)
        self.l_orderPrice_2.setGeometry(QtCore.QRect(180, 10, 54, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_orderPrice_2.sizePolicy().hasHeightForWidth())
        self.l_orderPrice_2.setSizePolicy(sizePolicy)
        self.l_orderPrice_2.setObjectName(_fromUtf8("l_orderPrice_2"))
        self.l_orderVolume_2 = QtGui.QLabel(self.groupBox_4)
        self.l_orderVolume_2.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.l_orderVolume_2.setObjectName(_fromUtf8("l_orderVolume_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(207, 200, 381, 91))
        self.groupBox_5.setStyleSheet(_fromUtf8("QGroupBox{background-color:rgb(229, 229, 229)}"))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.pb_sell_3 = QtGui.QPushButton(self.groupBox_5)
        self.pb_sell_3.setGeometry(QtCore.QRect(270, 40, 75, 23))
        self.pb_sell_3.setStyleSheet(_fromUtf8("QPushButton { background-color:#76EE00 }\n"
""))
        self.pb_sell_3.setObjectName(_fromUtf8("pb_sell_3"))
        self.pb_buy_3 = QtGui.QPushButton(self.groupBox_5)
        self.pb_buy_3.setGeometry(QtCore.QRect(180, 40, 75, 23))
        self.pb_buy_3.setStyleSheet(_fromUtf8("QPushButton { background-color: #FF0000}"))
        self.pb_buy_3.setObjectName(_fromUtf8("pb_buy_3"))
        self.le_stockCode_3 = QtGui.QLineEdit(self.groupBox_5)
        self.le_stockCode_3.setGeometry(QtCore.QRect(80, 10, 81, 20))
        self.le_stockCode_3.setText(_fromUtf8(""))
        self.le_stockCode_3.setMaxLength(6)
        self.le_stockCode_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_stockCode_3.setObjectName(_fromUtf8("le_stockCode_3"))
        self.l_stockCode_3 = QtGui.QLabel(self.groupBox_5)
        self.l_stockCode_3.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.l_stockCode_3.setObjectName(_fromUtf8("l_stockCode_3"))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.l_orderPrice_3 = QtGui.QLabel(self.groupBox_5)
        self.l_orderPrice_3.setGeometry(QtCore.QRect(180, 10, 54, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_orderPrice_3.sizePolicy().hasHeightForWidth())
        self.l_orderPrice_3.setSizePolicy(sizePolicy)
        self.l_orderPrice_3.setObjectName(_fromUtf8("l_orderPrice_3"))
        self.l_orderVolume_3 = QtGui.QLabel(self.groupBox_5)
        self.l_orderVolume_3.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.l_orderVolume_3.setObjectName(_fromUtf8("l_orderVolume_3"))
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(220, 73, 54, 12))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(133, 69, 81, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(270, 73, 54, 12))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        DockWdget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWdget)
        QtCore.QMetaObject.connectSlotsByName(DockWdget)

    def retranslateUi(self, DockWdget):
        DockWdget.setWindowTitle(_translate("DockWdget", "分级基金买卖", None))
        self.groupBox.setTitle(_translate("DockWdget", "行情数据显示", None))
        self.pb_harden.setText(_translate("DockWdget", "涨停价", None))
        self.pb_limit.setText(_translate("DockWdget", "跌停价", None))
        self.label.setText(_translate("DockWdget", "卖5", None))
        self.label_2.setText(_translate("DockWdget", "卖4", None))
        self.label_3.setText(_translate("DockWdget", "卖3", None))
        self.label_4.setText(_translate("DockWdget", "卖2", None))
        self.label_5.setText(_translate("DockWdget", "卖1", None))
        self.label_6.setText(_translate("DockWdget", "买1", None))
        self.label_7.setText(_translate("DockWdget", "买2", None))
        self.label_8.setText(_translate("DockWdget", "买3", None))
        self.label_9.setText(_translate("DockWdget", "买4", None))
        self.label_10.setText(_translate("DockWdget", "买5", None))
        self.label_11.setText(_translate("DockWdget", "最新价", None))
        self.groupBox_2.setTitle(_translate("DockWdget", "交易操作", None))
        self.l_orderPrice.setText(_translate("DockWdget", "委托价格：", None))
        self.l_stockCode.setText(_translate("DockWdget", "B基金代码：", None))
        self.l_orderVolume.setText(_translate("DockWdget", "委托数量：", None))
        self.pb_sell.setText(_translate("DockWdget", "卖出(S)", None))
        self.pb_buy.setText(_translate("DockWdget", "买入(B)", None))
        self.checkBox.setText(_translate("DockWdget", "联动A", None))
        self.pb_useCode4.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode8.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode3.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode.setText(_translate("DockWdget", "常用代码：", None))
        self.pb_useCode1.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode7.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode6.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode5.setText(_translate("DockWdget", "000001", None))
        self.groupBox_3.setTitle(_translate("DockWdget", "组合交易操作", None))
        self.label_12.setText(_translate("DockWdget", "份数：", None))
        self.pushButton_2.setText(_translate("DockWdget", "卖B+A", None))
        self.pushButton_8.setText(_translate("DockWdget", "买B+A", None))
        self.pushButton_9.setText(_translate("DockWdget", "合并", None))
        self.pushButton_10.setText(_translate("DockWdget", "买+合", None))
        self.pushButton_11.setText(_translate("DockWdget", "快合", None))
        self.pushButton_12.setText(_translate("DockWdget", "快拆B", None))
        self.pushButton_13.setText(_translate("DockWdget", "申购", None))
        self.pushButton_14.setText(_translate("DockWdget", "拆分", None))
        self.pushButton_15.setText(_translate("DockWdget", "拆+卖", None))
        self.pushButton_16.setText(_translate("DockWdget", "快拆", None))
        self.pushButton_17.setText(_translate("DockWdget", "快拆S", None))
        self.pushButton_18.setText(_translate("DockWdget", "赎回", None))
        self.pb_useCode4_2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode8_2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode3_2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode2_2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode_2.setText(_translate("DockWdget", "常用数量：", None))
        self.pb_useCode1_2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode7_2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode6_2.setText(_translate("DockWdget", "000001", None))
        self.pb_useCode5_2.setText(_translate("DockWdget", "000001", None))
        self.pb_buy_2.setText(_translate("DockWdget", "买入(B)", None))
        self.pb_sell_2.setText(_translate("DockWdget", "卖出(S)", None))
        self.checkBox_2.setText(_translate("DockWdget", "联动B", None))
        self.l_stockCode_2.setText(_translate("DockWdget", "A基金代码：", None))
        self.l_orderPrice_2.setText(_translate("DockWdget", "委托价格：", None))
        self.l_orderVolume_2.setText(_translate("DockWdget", "委托数量：", None))
        self.pb_sell_3.setText(_translate("DockWdget", "卖出(S)", None))
        self.pb_buy_3.setText(_translate("DockWdget", "买入(B)", None))
        self.l_stockCode_3.setText(_translate("DockWdget", "母基金代码：", None))
        self.label_13.setText(_translate("DockWdget", "母基金最小拆合单位：", None))
        self.l_orderPrice_3.setText(_translate("DockWdget", "委托价格：", None))
        self.l_orderVolume_3.setText(_translate("DockWdget", "委托数量：", None))
        self.label_14.setText(_translate("DockWdget", "AB比例：", None))
        self.label_15.setText(_translate("DockWdget", "50,000份", None))
        self.label_16.setText(_translate("DockWdget", "6:4", None))

